gkd-kit/subscription

- src/apps/com.ct.client.ts
> fix: 中国电信开屏广告跳过规则

- src/apps/com.baidu.youavideo.ts
This reverts commit 7aa6df41744a488d29ebe7ea4e3a5ac7e9c71f64.
> Revert "发现了一种新的开屏广告，增加了一条匹配规则 (#70)"

- src/apps/com.babytree.apps.pregnancy.ts
> feat(宝宝树孕育): 开屏广告以及其它偶发广告

- src/apps/com.sankuai.meituan.ts
> feat(美团): 若干弹窗

- src/apps/com.netease.newsreader.activity.ts
- 开屏广告
- 版本更新弹窗
- 开启系统推送弹窗
- 开启系统推送提示信息
- 首页信息流广告
> feat(网易新闻)

- src/apps/com.qidian.QDReader.ts
- 更新弹窗
- 青少年模式弹窗
- 活动弹窗
- 系统推送提示信息
> feat(起点读书)

- src/apps/com.xingluo.allcolor.ts
> feat(一起来涂色)

- src/apps/fm.qingting.qtradio.ts
> feat(蜻蜓FM)

- src/apps/com.maque.app.ts
> feat(麻雀省钱)

- src/apps/com.kmxs.reader.ts
- 开屏广告
- 阅读页面底部广告
- 阅读结束后显示的广告
- 签到弹窗
- 右侧悬浮红包（无法触发，原因未知）
> feat(七猫免费小说)

- src/apps/com.tiqiaa.icontrol.ts
> feat(遥控精灵)

- src/apps/com.mxtech.videoplayer.ad.ts
> feat(MX播放器)

- src/apps/com.tencent.weread.ts
> feat(微信读书)

- src/apps/com.umetrip.android.msky.app.ts
> feat(航旅纵横)

- src/apps/com.baidu.BaiduMap.ts
- 地图上方黄页横幅
- 打车界面-右侧悬浮球
- 美食大礼包弹窗
- 酒店提前订弹窗
> feat(百度地图)

- src/apps/com.cnspeedtest.globalspeed.ts
> feat(全球网测)

- src/apps/cn.com.ruijie.magicbox.ts
> feat(无线魔盒)

- src/apps/com.eastmoney.android.fund.ts
> feat(天天基金)

- src/apps/com.sf.activity.ts
> feat(顺丰速运)

- src/apps/com.xiaomi.vipaccount.ts
> feat(小米社区)

- src/apps/com.xyhui.ts
> feat(PU口袋校园)

- src/apps/com.baidu.netdisk.ts
- 活动弹窗
- 首页banner广告
- 首页热门广告
- 我的页面-限时福利
> feat(百度网盘)

- src/apps/com.autonavi.minimap.ts
- 首页-地图页面上方消息提醒
- 首页-签到卡片
- 加油页面-优惠券弹窗
> feat(高德地图)

- src/apps/com.daysko.safp.ts
- 谷歌广告-全屏广告
- 谷歌广告-视频广告
- 谷歌广告-页面底部广告（底部广告难以去除，原因未知）
> feat(7天澳門統考)

- src/apps/com.zgnet.eClass.ts
> feat(掌医课堂): 开屏广告

- src/apps/com.wondertek.paper.ts
> feat(澎湃新闻): 开屏广告

- src/apps/com.huawei.android.thememanager.ts
> feat(华为主题): 主题详情、信息流广告、横幅

- src/apps/com.lphtsccft.ts
> feat(涨乐财富通)

- src/apps/com.cmbchina.ccd.pluto.cmbActivity.ts
- 开屏广告
- 更新弹窗
- 首页弹窗
- 右侧悬浮广告
- 消息页面-通知开关
> feat(掌上生活)

- src/apps/make.more.r2d2.cellular_z.ts
> feat(Cellular-Z): 开屏广告

- src/apps/com.xiaomi.shop.ts
> feat(小米商城)

- src/apps/tv.danmaku.bili.ts
> feat(哔哩哔哩)

- src/apps/com.huawei.android.thememanager.ts
> feat(华为主题): enhance

- src/apps/com.ai.obc.cbn.app.ts
> feat(中国广电)

- src/apps/vstc.AKCXKJ.client.ts
> feat(FOWL)

- src/apps/com.netease.mail.ts
> feat(网易邮箱大师)

- src/apps/com.huawei.android.thememanager.ts
> feat(华为主题)

- src/apps/com.huawei.health.ts
> feat(华为运动健康)

- src/apps/com.huawei.search.ts
> feat(华为智慧搜索): 下拉广告

- src/apps/com.tiqiaa.icontrol.ts
- src/apps/com.weaver.emobile7.ts
> feat(Emobile7)

- src/apps/com.zjwh.android_wh_physicalfitness.ts
- 优量汇广告
- 百青藤广告
- 快手广告
- 第三方SDK广告
> feat(运动世界校园)

- src/apps/com.tencent.qqmusic.ts
> feat(QQ音乐)

- src/apps/com.xiaomi.market.ts
> feat(应用商店)

- src/apps/com.estrongs.android.pop.ts
> feat(ES文件浏览器)

- src/apps/com.huawei.browser.ts
> feat(华为浏览器)

- src/apps/com.huawei.appmarket.ts
> feat(华为应用市场)

- src/apps/com.gtgj.view.ts
> feat(高铁管家)

- src/apps/com.excean.splay.ts
> feat(OurPlay加速器)

- src/apps/com.citiccard.mobilebank.ts
> feat(动卡空间)

- src/apps/com.ss.android.article.news.ts
> feat(今日头条)

- src/apps/com.tbc.android.defaults.ts
> feat(云端学习)

- src/apps/com.android.bankabc.ts
> feat(中国农业银行)

- src/apps/com.yitong.mbank.psbc.ts
> feat(邮储银行)

- src/apps/net.csdn.csdnplus.ts
- 开屏广告
- 更新弹窗
- 信息流广告
- 请求推送通知弹窗
> feat(CSDN)

- src/apps/com.smzdm.client.android.ts
> feat(什么值得买)

- src/apps/com.unionpay.ts
> feat(云闪付): 定位请求悬浮框，定位请求弹窗，消息通知弹窗，右侧悬浮广告

- src/apps/com.csg.palmhall.ts
> feat(南网在线)

- src/apps/com.tencent.qqlive.ts
- 更新弹窗
- 首页-顶部广告卡片
- 片头广告
- 个人中心-广告卡片
- 请求开启推送通知弹窗
- 开屏广告（新增几组规则、补充快照）
> feat(腾讯视频)

- src/apps/com.feicui.vdhelper.ts
> feat(翡翠视频)

- src/apps/com.netease.cloudmusic.ts
> feat(网易云音乐)

- src/apps/com.youku.phone.ts
> feat(优酷视频)

- src/apps/com.ecitic.bank.mobile.ts
> feat(中信银行)

- src/apps/com.ximalaya.ting.android.ts
- 首页-推荐列表广告（新增一条规则）
- 播放页面-底部推荐列表-夹杂广告（关闭广告后，控件仍然存在但不可见，使用 visibleToUser=true 进行限定，防止关闭之后继续触发规则）
> feat(喜马拉雅)

- src/apps/com.seebaby.ts
> feat(掌通家园)

- src/apps/com.ifeng.news2.ts
- 开屏广告
- 信息流广告
- 请求位置权限弹窗（默认关闭）
> feat(凤凰新闻)

- src/apps/cmb.pb.ts
- 朝朝宝-广告弹窗
- 请求定位权限弹窗（默认关闭）
- 开屏广告（补充快照）
> feat(招商银行)

- src/apps/com.jin10.ts
- 更新弹窗
- 首页广告弹窗
- 快讯页面-广告弹窗
- 会员页面-顶部广告（默认关闭）
> feat(金十数据)

- src/apps/com.eastmoney.android.berlin.ts
- 开屏广告
- 更新弹窗
- 请求通知权限提示信息（默认关闭）
> feat(东方财富)

- src/apps/com.ss.android.article.lite.ts
- 首页-红包弹窗
- 首页-右侧悬浮广告
- 首页-你可能感兴趣的人
- 任务页面-签到弹窗
- 任务页面-右侧悬浮红包
- 任务页面-答题弹窗
- 搜索页面-搜索得金币弹窗
> feat(头条搜索极速版)

- src/apps/com.gotokeep.keep.ts
- 青少年模式弹窗
- 首页广告弹窗
- 首页信息流广告
- 运动购页面-广告弹窗
- 开屏广告（补充快照）
> feat(Keep)

- src/apps/io.iftech.android.box.ts
- 开屏广告
- 更新弹窗
- 第三方 SDK 广告
- 会员限时优惠弹窗（默认关闭）
> feat(小组件盒子)

- src/apps/com.zhaopin.social.ts
> feat(智联招聘)

- src/apps/gov.pianzong.androidnga.ts
- 社区-顶部广告
- 开屏广告（新增 activityId，快照）
- 话题-帖子列表广告（新增一条规则）
> feat(NGA玩家社区)

- src/apps/com.qinlin.edoor.ts
- 首页顶部广告
- 开门有奖弹窗（默认关闭）
- 获得金币弹窗（默认关闭）
> feat(亲邻开门)

- src/apps/com.woapp.hebei.ts
> feat(联通智家)

- src/apps/com.qq.ac.android.ts
- 开屏广告
- 青少年模式弹窗
- 漫画阅读页面-左侧悬浮广告
> feat(腾讯动漫)

- src/apps/com.samsung.android.voc.ts
> feat(盖乐世社区)

- src/apps/cn.net.shizheng.study.ts
> feat(365时政)

- src/apps/com.dep.biguo.ts
- 开屏广告
- 更新弹窗
- 首页广告弹窗
- 请求定位权限弹窗（默认关闭）
> feat(自考笔果题库)

- CONTRIBUTING.md
- src/apps/cn.edu.hit.welink.ts
增加规则：哈工大APP-开屏页面
并修改CONTRIBUTING.md，对如何获取快照链接进行说明
>  feat: 哈工大APP-开屏页面(虽然除了本校生应该没人用)

- src/apps/com.yaerxing.fkst.ts
> feat(疯狂刷题)

- src/apps/cn.xuexi.android.ts
> feat(学习强国)

- src/apps/com.maidu.gkld.ts
- 更新弹窗
- 首页右侧悬浮广告
- 请求通知权限弹窗（默认关闭）
> feat(公考雷达)

- src/apps/cn.speedtest.lite.ts
> feat(网速管家极速版)

- src/apps/com.huatu.handheld_huatu.ts
- 开屏广告
- 首页广告弹窗
- 请求通知权限弹窗（默认关闭）
> feat(华图在线)

- src/apps/com.xiaomi.gamecenter.ts
> feat(小米游戏中心)

- src/apps/com.boohee.one.ts
- 开屏广告
- 更新弹窗
- 发现页广告弹窗
- 请求开启通知权限弹窗（默认关闭）
> feat(薄荷健康)

- src/apps/com.ruanmei.ithome.ts
> feat(IT之家)

- src/apps/com.tencent.mobileqq.ts
> feat(QQ): 好友热播

- src/apps/com.cebbank.mobile.cemb.ts
> feat(光大银行)

- src/apps/com.jd.jdlite.ts
> feat(京喜特价)

- src/apps/cn.lezhi.speedtest.ts
> feat(网速管家)

- src/apps/com.pingan.carowner.ts
> feat(平安好车主)

- src/apps/cn.kuwo.player.ts
> feat(酷我音乐)

- src/apps/com.jdd.motorfans.ts
> feat: 新增摩托范弹窗规则

- src/apps/com.huawei.smarthome.ts
> feat(智慧生活)

- src/apps/com.icbc.ts
> feat(中国工商银行)

- src/apps/com.mobi.shtp.ts
> feat(上海交警)

- src/apps/cn.com.hkgt.gasapp.ts
> feat(易捷加油)

- src/apps/com.qihoo.dr.ts
> feat(360行车助手)

- src/apps/cn.com.shbank.mper.ts
> feat(上海银行)

- src/apps/com.spdbccc.app.ts
> feat(浦大喜奔)

- src/apps/com.srcb.pmbank.ts
> feat(上海农商银行)

- src/apps/cn.com.spdb.mobilebank.per.ts
> feat(浦发银行)

- src/apps/com.sinyee.babybus.recommendapp.ts
> feat(宝宝巴士)

- src/apps/com.qh.tesla.ts
> feat(巧虎官方)

- src/apps/com.iflytek.aistudyclient.parentcontrol.ts
- 开屏广告（注意：选中的目标是快照中的一片区域，不确定能否达到预期目的）
> feat(讯飞AI学)

- src/apps/com.weico.international.ts
> feat(微博轻享版)

- src/apps/com.sgcc.wsgw.cn.ts
> feat(网上国网)

- src/apps/cn.xiaochuankeji.zuiyouLite.ts
> feat(皮皮搞笑)

- src/apps/com.huawei.music.ts
> feat(华为音乐)

- src/apps/com.bankcomm.Bankcomm.ts
> feat(交通银行)

- src/apps/com.youdao.note.ts
> feat(有道云笔记)

- src/apps/com.xiaomi.mico.ts
> feat(小爱音箱)

- src/apps/com.tmri.app.main.ts
> feat(交管12123)

- src/apps/com.tencent.news.ts
- 开屏广告
- 信息流广告
- 广告、活动弹窗
- 请求通知权限弹窗（默认关闭）
> feat(腾讯新闻)

- src/apps/com.android.updater.ts
> feat(系统更新)

- src/apps/com.autonavi.minimap.ts
> improvement(高德地图)

- src/apps/com.firebear.androil.ts
> feat(小熊油耗)

- src/apps/com.cnki.view.ts
> feat(知网文化)

- src/apps/com.qq.qcloud.ts
> feat(腾讯微云)

- src/apps/com.chinamobile.mcloud.ts
> feat(中国移动云盘)

- src/apps/cn.com.cmbc.newmbank.ts
> feat(民生银行)

- src/apps/com.xmcy.hykb.ts
> feat(好游快爆)

- src/apps/com.lphtsccft.zlqqt2.ts
> feat(涨乐全球通)

- src/apps/com.Kingdee.Express.ts
> feat(快递100)

- src/apps/com.xueqiu.fund.ts
> feat(雪球基金)

- src/apps/com.soft.blued.ts
> feat(Blued)

- src/apps/com.xiaomi.account.ts
> feat(小米账号)

- src/apps/com.hihonor.phoneservice.ts
> feat(我的荣耀)

- src/apps/com.HaoTuBang.H3DBodyFree.ts
> feat(3Dbody解剖)

- src/apps/com.ponyemu.main.ts
> feat(小马模拟器)

- src/apps/com.baidu.tieba.ts
> chore(百度贴吧)

- src/apps/com.tencent.qt.qtl.ts
> feat(掌上英雄联盟)

- src/apps/me.zhouzhuo810.zznote.ts
> feat(小周便签)

- src/apps/com.instagram.android.ts
> feat(Instagram)

- src/apps/com.google.android.documentsui.ts
> feat(Android 系统文件选择器)

- src/apps/online.bangumi.ts
> feat(アニメ新番組)

- src/apps/npgl.jsitcx.xlpqi.ts
- 开屏广告
- 应用内第三方 SDK 广告弹窗
- 应用内第三方 SDK 广告卡片
> feat(NP管理器)

- src/apps/so.tita.ts
- 开屏广告
- 应用内第三方 SDK 广告
- 观看视频去除广告提示弹窗
> feat(tita搜索)

- src/apps/com.qq.reader.ts
> feat(QQ阅读)

- src/apps/com.miui.packageinstaller.ts
> feat(MIUI 应用包管理组件)

- src/apps/com.igpsport.igpsportandroid.ts
> feat(iGPSPORT)

- src/apps/com.hunantv.imgo.activity.ts
- 【首页推荐流-卡片广告】添加 prekeys
- 【应用内广告弹窗】
- 【右侧悬浮广告】
> feat(芒果TV)

- src/apps/com.alibaba.ailabs.tg.ts
> feat(天猫精灵): 开屏广告

- src/apps/com.huawei.himovie.ts
> feat(华为视频): 开屏广告

- src/apps/com.xiaohu.olevodmobile.ts
> feat(欧乐影院)

- src/apps/org.gushiwen.gushiwen.ts
> feat(古诗文网)

- src/apps/com.example.businesshall.ts
> feat(中国移动浙江)

- src/apps/com.jsmcc.ts
> feat(中国移动江苏)

- src/apps/cn.soulapp.android.ts
> feat(Soul)

- src/apps/com.android.browser.ts
> feat(小米浏览器)

- src/apps/com.kurogame.kjq.ts
> feat(库街区): 开屏广告

- src/apps/com.cubic.autohome.ts
shanlan [feat(汽车之家): 弹窗广告](https://github.com/shanlanCoding/subscription/commit/d1b521c58355636b6ac0cb55fd4aa127a3eb5214)
> feat(汽车之家): 弹窗广告

- src/apps/com.xiaomi.youpin.ts
> feat(小米有品)

- src/apps/com.qiyi.video.ts
> feat(爱奇艺): 通知弹窗

- src/apps/com.jujie.xbreader.ts
> feat(小白PDF阅读器)

- src/apps/com.taptap.ts
> feat(TapTap)

- src/apps/com.jingdong.app.mall.ts
> feat(京东): 消息通知弹窗

- src/apps/com.saicmotor.tocapp.ts
> feat(上汽荣威): 开屏广告

- src/apps/cn.hsa.app.ts
> feat(国家医保服务平台): 开屏广告

- src/apps/com.jf.my.ts
- 【版本升级弹窗】 - 规则优化
- 【首页-广告弹窗】- 新增
> feat(蜜源): 

- src/apps/com.ss.android.auto.ts
> feat(懂车帝): 请求推送通知弹窗

- src/apps/com.xiaomi.vipaccount.ts
> feat(小米社区): 开屏广告

- src/apps/com.huawei.search.ts
> feat(华为智慧搜索)

- src/apps/com.newcapec.mobile.ncp.ts
1、升级提示。自动点击【X】
2、密码过期提示。自动点击【取消】
#710
> feat( 完美校园 ): 规则适配

- src/apps/com.netease.cloudmusic.ts
> feat(网易云音乐): 增加免费听歌弹窗规则

- src/apps/com.taobao.litetao.ts
> feat(淘特): 版本升级弹窗

- src/apps/com.qooapp.qoohelper.ts
> feat( QooApp ): 开屏广告

- src/apps/cn.TuHu.android.ts
> feat(途虎养车)

- src/apps/com.mfcloudcalculate.networkdisk.ts
> feat(123云盘)

- src/apps/com.miaoying.appmy.ts
> feat(天空影视)

- src/apps/com.qihoo.camera.ts
> feat(360摄像机)

- src/apps/com.zhiyin.qingdan.dashixiong.ts
#789 
- 【开屏广告】
- 【应用内广告弹窗】
- 【公告弹窗】（默认关闭）
> feat(大师兄影视)

- src/apps/com.miui.cloudservice.ts
> feat(小米云服务)

- src/apps/com.twitter.android.ts
> feat(X) 【信息流广告-帖子详情页、搜索页】优化规则

- src/apps/com.voice.broadcastassistant.ts
> feat(通知播报助手):开屏广告跳过

- src/apps/com.onethingcloud.android.ts
> feat(网心云)【开屏广告】

- src/apps/cn.soulapp.android.ts
> feat(Soul): 开屏广告- 规则优化

- src/apps/com.miui.player.ts
> feat(小米音乐): 开屏广告 - 规则优化

- src/apps/cmccwm.mobilemusic.ts
> feat(咪咕音乐): 开屏广告

- src/apps/com.copymanga.app.ts
> feat(拷貝漫畫): 开屏广告 - 规则优化

- src/apps/com.realtech.xiaocan.ts
> feat(小蚕霸王餐): 开屏广告 - 规则优化

- src/apps/com.mangshe.tvdown.ts
> feat(蟒蛇下载): 开屏广告

- src/apps/com.firebear.androil.ts
> feat(小熊油耗): 开屏广告 - 规则优化

- src/apps/com.rytong.hnair.ts
> feat(海南航空)

- src/apps/com.gstarmc.android.ts
> feat(CAD看图王): 开屏广告

- src/apps/com.lemon.faceu.ts
> feat(Faceu激萌): 开屏广告

- src/apps/com.weico.international.ts
> feat(微博轻享版): 【主页-推荐流广告】 - 规则优化

- src/apps/com.gentle.ppcat.ts
> feat(皮皮喵): 开屏广告 - 规则优化

- src/apps/com.cnki.client.ts
> feat(手机知网): 开屏广告,更新弹窗

- src/apps/com.picooc.ts
> feat(PICOOC): 开屏广告

- src/apps/com.lovebizhi.wallpaper.ts
> feat(爱壁纸): 开屏广告

- src/apps/com.jincheng.supercaculator.ts
> feat(全能计算器): 开屏广告

- src/apps/com.copymanga.app.ts
> Com.copymanga.app

- src/apps/com.baidu.netdisk.ts
Com.baidu.netdisk
From https://github.com/gkd-kit/subscription/issues/907
默认关闭
> feat(百度网盘): 关闭更新提示 

- src/apps/com.cn21.ecloud.ts
> feat( 天翼云盘 ): 开屏广告，首页弹窗

- src/apps/com.xunlei.downloadprovider.ts
> feat(迅雷): 传输界面-广告弹窗

- src/apps/com.p1.mobile.putong.ts
https://github.com/gkd-kit/subscription/issues/918
Create com.p1.mobile.putong.ts
> feat(探探): 开屏广告

- src/apps/com.molink.john.hummingbird.ts
> feat(bebird)

- src/apps/com.zmzx.college.search.ts
#924 
- 开屏广告
- 首页-推送通知
- 我的-弹窗广告
> feat(大学搜题酱)

- src/apps/com.lptiyu.tanke.ts
https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/134
- 弹窗广告（优化规则）
> feat(步道乐跑)

- src/apps/com.bankcomm.Bankcomm.ts
https://github.com/gkd-kit/subscription/issues/940
按issue的快照来看, 唯一的不同就是activityIds
> feat(交通银行): 版本升级弹窗

- src/apps/com.google.android.youtube.ts
https://github.com/gkd-kit/subscription/issues/938
> feat(Youtube): 赞助商广告 & Premium广告

- src/apps/com.glyh.mbank.pro.ts
https://github.com/gkd-kit/subscription/issues/939
> feat(桂林银行): 开屏广告

- src/apps/com.tencent.mobileqq.ts
> feat(QQ): QQ小程序开屏广告

- src/apps/com.dmzjsq.manhua.ts
> feat(动漫之家社区): 广告弹窗

- src/apps/com.ximalaya.ting.android.ts
https://github.com/gkd-kit/subscription/issues/959
> feat(喜马拉雅): 开屏广告

- src/apps/com.miui.packageinstaller.ts
> feat(应用包管理组件)

- src/apps/com.quqi.quqioffice.ts
> feat(曲奇云盘)

- src/apps/com.UCMobile.ts
- 信息流广告（优化规则）
- 请求通知权限弹窗
- 请求添加桌面快捷方式权限弹窗
> feat(UC浏览器)

- src/apps/com.zmzx.college.search.ts
> fix(大学搜题酱)

- src/apps/com.dragon.read.ts
> feat(番茄免费小说): 广告弹窗

- src/apps/com.lolaage.tbulu.tools.ts
> feat(两步路户外助手)

- src/apps/com.glodon.constructioncalculators.ts
> feat(建工计算器)

- src/apps/com.netease.gl.ts
> feat(网易大神)

- src/apps/com.bw30.zsch.ts
> feat(四川航空)

- src/apps/com.feeyo.vz.pro.cdm.ts
> feat(飞常准业内版)

- src/apps/com.lovebizhi.wallpaper.ts
> feat(爱壁纸): 开屏广告-规则优化

- src/apps/com.viva.note.ts
https://github.com/gkd-kit/subscription/issues/963
针对com.viva.note
> feat(囧次元): 开屏, 应用内

- src/apps/com.wudaokou.hippo.ts
https://github.com/gkd-kit/subscription/issues/997
> feat(盒马): 开屏广告

- src/apps/com.youxiake.ts
https://github.com/gkd-kit/subscription/issues/1001
> feat(游侠客旅行): 开屏广告

- src/apps/com.sdu.didi.psnger.ts
https://github.com/gkd-kit/subscription/issues/992
> fix(滴滴出行): 开屏广告增加界面ID

- src/apps/com.tencent.zebra.ts
> feat(水印相机)

- src/apps/com.dmzjsq.manhua.ts
> feat(动漫之家社区)

- src/apps/chuxin.shimo.shimowendang.ts
> feat(石墨文档)

- src/apps/com.mj.mjyd.ts
- 【广告弹窗】- 规则优化  [#949](https://github.com/gkd-kit/subscription/pull/949#issuecomment-1761691054)
> feat(追漫大全): 广告弹窗-规则优化

- src/apps/com.shuqi.controller.ts
> feat(书旗小说)

- src/apps/com.duowan.kiwi.ts
> feat(虎牙) 直播间悬浮广告

- src/apps/com.jingdong.app.mall.ts
> feat(京东) 京东账号登录授权

- src/apps/com.jd.iots.ts
> feat(京东小家) 开屏广告

- src/apps/com.sf.activity.ts
> feat(顺丰速运) 开屏广告（完善规则）

- src/apps/com.aster.zhbj.ts
> feat(喵上漫画) 应用内广告弹窗

- src/apps/com.qiekj.user.ts
> feat(胖乖生活) 开屏广告

- src/apps/com.example.maintenancemaster.ts
> feat(维护大师)

- src/apps/com.banjixiaoguanjia.app.ts
> feat(班级小管家) 开屏广告，应用内广告卡片

- src/apps/com.baidu.tieba_mini.ts
> feat(贴吧极速版) 首页-信息流广告

- src/apps/cn.guancha.app.ts
https://github.com/gkd-kit/subscription/issues/1075
> feat(观察者网): 开屏广告

- src/apps/csii.com.qny.ts
https://github.com/gkd-kit/subscription/issues/1079
> feat(黔农云): 开屏广告

- src/apps/com.dragon.read.ts
> feat(番茄免费小说): 阅读页面底部广告- 规则优化

- src/apps/com.dragon.read.ts
> feat(番茄免费小说) 阅读页面底部广告（完善规则）

- src/apps/com.msnothing.airpodsking.ts
> feat(Pods King) 开屏广告

- src/apps/com.tencent.mtt.ts
#1077 
- 小说阅读页面-卡片广告
- 小说阅读页面-视频广告
> feat(QQ浏览器) 小说阅读页面广告

- src/apps/bin.mt.plus.ts
> feat(MT管理器) 更新弹窗

- src/apps/com.xyhui.ts
- 对 开屏广告、首页-优量汇弹窗广告、首页-浮窗广告 添加执行 quickFind
- 添加跳过升级提示
> feat(PU口袋校园): 规则优化、添加跳过升级提示

- src/apps/com.bilibili.studio.ts
> feat(必剪): 通知权限请求规则优化

- src/apps/com.copymanga.app.ts
com.copymanga.app
稍微修改一下限制条件提高兼容性。
> fix(拷贝漫画): 优化右下角关闭

- src/apps/com.baidu.BaiduMap.ts
#1096 
- 打车界面-新人红包弹窗
- 升级更新弹窗
- 地图上方黄页横幅 规则优化
- 请求定位弹窗 规则优化
- 添加quickFind：地图上方黄页横幅、打车界面-右侧悬浮球、美食大礼包弹窗、酒店提前订弹窗、请求定位弹窗、打车界面-新人红包弹窗、升级更新弹窗
> feat(百度地图): 规则优化、红包弹窗、升级更新弹窗

- src/apps/com.able.wisdomtree.ts
> feat(知到): 开屏广告、消息推送通知

- src/apps/com.xtuone.android.syllabus.ts
> feat(超级课程表)

- src/apps/com.umetrip.android.msky.app.ts
> feat(航旅纵横): 规则优化、酒店-弹窗广告

- src/apps/com.sankuai.meituan.ts
> feat(美团): 请求定位弹窗-规则优化

- src/apps/com.youloft.icloser.ts
> feat(心动日常): 开屏广告

- src/apps/com.kuaikan.comic.ts
> feat(快看漫画): 漫画界面-底部广告弹窗

- src/apps/com.svw.sc.mos.ts
https://github.com/gkd-kit/subscription/issues/1122
> feat(上汽大众): 新增 开屏广告跳过

- src/apps/com.gspace.android.ts
- 【开屏广告】- 规则优化
- 【主页面上方广告】- 规则优化
#1109
@lisonge  `matchLauncher:true, `是否可替代`activityIds: 'com.huawei.android.launcher.unihome.UniHomeLauncher',`
> feat(gspace): 【开屏广告】【主页面上方广告】

- src/apps/com.hanweb.android.zhejiang.activity.ts
> feat(浙里办): 【开屏广告】

- src/apps/com.ct.client.ts
- 规则优化: 使用quickFind
- 业务办理-弹窗广告
- 查询办理页面-浮窗广告
> feat(中国电信): 规则优化、业务办理-弹窗广告

- src/apps/com.cainiao.wireless.ts
> feat(菜鸟): 包裹页面-弹窗广告、包裹页面-地图底部横条广告

- src/apps/com.eg.android.AlipayGphone.ts
https://github.com/gkd-kit/subscription/issues/1136
从外部转入时候的ActivityId是Launcher
> fix(支付宝)：花呗升级提示

- src/apps/com.hihonor.magichome.ts
https://github.com/gkd-kit/subscription/issues/1138
> feat(荣耀智慧空间): 关闭更新提示

- src/apps/com.vanke.activity.ts
> feat(住这儿): 开屏广告

- src/apps/com.shanghaigm.android.mycadillac.ts
> feat(MyCadillac) 开屏广告

- src/apps/com.youloft.icloser.ts
> feat(心动日常) 开屏广告

- src/apps/com.coolapk.market.ts
#1144 
- 开屏广告适配
- 规则优化(使用quickFind)
> feat(酷安): 开屏广告规则优化

- src/apps/com.kugou.android.lite.ts
> feat(酷狗概念版) 开屏广告

- src/apps/com.tencent.mm.ts
#1147 
- 朋友圈广告规则优化
- 网页版文件传输助手扫码自动授权 规则优化(使用quickFind)
> feat(微信): 网页版文件传输助手扫码规则优化

- src/apps/com.lucky.luckyclient.ts
> feat(瑞幸咖啡): 超值换购, quickFind, matchLauncher

- src/apps/com.yuque.mobile.android.app.ts
> fix(语雀): 关闭横幅

- src/apps/com.huachenjie.shandong_school.ts
https://github.com/gkd-kit/subscription/issues/1156
> feat(闪动校园): 开屏广告

- src/apps/zhongxinjiantou.szkingdom.android.newphone.ts
https://github.com/gkd-kit/subscription/issues/1158
> feat(蜻蜓点金): 开屏广告, 通知权限

- src/apps/com.iflytek.inputmethod.ts
https://github.com/gkd-kit/subscription/issues/1166
> feat(讯飞输入法): 开屏广告

- src/apps/com.flutter3.ctangxin.vf0egg.ts
> feat(糖心Vlog)

- src/apps/com.huawei.android.totemweather.ts
> feat(华为天气) 开屏广告

- src/apps/com.baidu.BaiduMap.ts
#1059 
- 开屏广告规则优化
- 打车界面-弹窗广告规则优化
> feat(百度地图): 打车界面-弹窗广告；开屏广告规则优化

- src/apps/com.sdo.sdaccountkey.ts
> feat(叨鱼): 开屏广告

- src/apps/com.sina.weibo.ts
#1181 
- 评论区博主内容推荐规则优化
- 规则优化(使用quickFind)
> feat(微博): 评论区博主内容推荐规则优化

- src/apps/com.xiaomi.smarthome.ts
https://github.com/gkd-kit/subscription/issues/1203
> fix(米家): 温度误触修复

- src/apps/com.ksf.yyx.ts
> feat(OmoFun): 插屏广告- 规则优化

- src/apps/com.sina.weibo.ts
> feat(微博) 请求定位权限弹窗

- src/apps/com.aster.zhbj.ts
> fix(喵上漫画):增加跳过开屏广告

- src/apps/com.miui.packageinstaller.ts
> feat(应用包管理组件): 自动更新应用（完善规则）

- src/apps/com.xinhang.mobileclient.ts
#1218 
- 开屏广告
- 应用内广告弹窗
- 右侧悬浮广告
> feat(中国移动河南): 开屏广告、应用内广告弹窗、右侧悬浮广告

- src/apps/com.huachenjie.shandong_school.ts
> feat(闪动校园): 开屏广告（完善规则）

- src/apps/tv.danmaku.bilibilihd.ts
> feat(哔哩哔哩HD): 开屏广告

- src/apps/io.dcloud.H55BDF6BE.ts
> feat(甬派): 开屏广告

- src/apps/im.xingzhe.ts
> feat(行者骑行): 开屏广告

- src/apps/air.tv.douyu.android.ts
> fix( 斗鱼 ): 播放界面-全屏播放规则优化

- src/apps/com.miui.packageinstaller.ts
> feat(应用包管理组件): 自动更新应用（优化规则）

- src/apps/com.oplus.appdetail.ts
> feat(Color OS 应用安装器): 自动安装应用

- src/apps/com.tencent.androidqqmail.ts
- src/apps/com.vyou.vcameraclient.ts
> feat(盯盯拍): 开屏广告

- src/apps/com.gamersky.ts
> fix(游民星空): 添加不同版本的匹配规则

- src/apps/com.tencent.androidqqmail.ts
- 开启通知提醒
- 广告邮件-列表卡片广告(使用quickFind)
> feat(qq邮箱): 开启通知提醒

- src/apps/net.pchome.kds.ts
> feat(kds宽带山): 应用内广告卡片

- src/apps/com.zuoyebang.knowledge.ts
> feat(作业帮家长版): 赏好评弹窗

- src/apps/com.citiccard.mobilebank.ts
> feat(动卡空间): 开屏广告

- src/apps/net.pchome.kds.ts
> feat(kds宽带山): 应用内广告卡片（完善规则）

- src/apps/com.mfw.roadbook.ts
https://github.com/gkd-kit/subscription/issues/1237
> feat(马蜂窝): 开屏广告

- src/apps/com.didapinche.booking.ts
https://github.com/gkd-kit/subscription/issues/1258
> feat(嘀嗒出行): 开屏广告

- src/apps/com.duowan.kiwi.ts
> fix(虎牙直播): 开屏广告-添加一种开屏广告情况

- src/apps/com.jd.jrapp.ts
https://github.com/gkd-kit/subscription/issues/1261
> feat(京东金融): 开屏广告

- src/apps/com.baidu.tieba.ts
- 帖子评论区广告卡片（优化规则）
#1286 
- 首页顶部广告卡片
- 应用内广告弹窗
> feat(百度贴吧): 帖子评论区广告卡片（优化规则）、首页顶部广告卡片、应用内广告弹窗

- src/apps/com.miui.packageinstaller.ts
- 自动第三方安装应用（完善规则）
- 自动安装应用（优化规则）
> feat(应用包管理组件): 自动第三方安装应用（完善规则）、自动安装应用（优化规则）

- src/apps/com.iflytek.inputmethod.ts
- https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/139
> feat(讯飞输入法): 开屏广告（补充规则）

- src/apps/client.android.yixiaotong.ts
https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/140
https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/141
- 开屏广告
- 应用内广告弹窗
- 应用内广告卡片
> feat(乐校通): 开屏广告、应用内广告弹窗、应用内广告卡片

- src/apps/com.unicde.smartcity_lyg.ts
> feat(我的连云港): 开屏广告

- src/apps/com.mipay.wallet.ts
> feat(小米钱包): 开屏广告

- src/apps/com.kuaitong.driver.ts
> feat(快通驾考): 开屏广告

- src/apps/com.hihonor.vmall.ts
> feat(荣耀商城): 应用内广告弹窗

- src/apps/cn.wenyu.bodian.ts
> feat(波点音乐): 开屏广告

- src/apps/com.xt.retouch.ts
> feat(醒图): 好评反馈

- src/apps/com.douban.frodo.ts
> feat(豆瓣): 【信息流广告】- 规则优化

- src/apps/com.leduoworks.gpstoolbox.ts
> feat(GPS工具箱)

- src/apps/com.tencent.mobileqq.ts
NT QQ 在电脑上点击确认登录时会弹出类似微信的确认登录界面
> feat(QQ): NT QQ 自动点击确认登录

- src/apps/com.xtc.watch.ts
> feat(小天才): 开启通知提醒

- src/apps/com.zmzx.college.search.ts
> feat(大学搜题酱): 教材-底部广告、升级弹窗

- src/apps/com.zhaopin.social.ts
> feat(智联招聘): 社区-弹窗广告、消息-开启消息通知

- src/apps/com.bilibili.comic.ts
> feat(哔哩哔哩漫画): 青少年模式弹窗、开屏广告(gkd-kit#1189)

- src/apps/com.cyl.musiccy.ou.ts
- src/apps/com.ksf.yyx.ts
原APP包名现已修改为com.cyl.musiccy.ou；
新增多个规则
> feat(OmoFun): 修改APP ID，开屏广告，首页通知，插屏广告

- src/apps/com.okcam.ookcam.ts
> 添加小鹰看看开屏广告

- src/apps/com.cainiao.wireless.ts
> feat(菜鸟): 开启消息弹窗

- src/apps/com.bw30.zsch.ts
> feat(四川航空): 开屏广告(补充activityIds)、升级弹窗

- src/apps/com.baidu.netdisk.ts
#1333 
- 更新提醒，通知权限规则规则优化
- 规则优化(使用quickFind)
> fix(百度网盘): 更新提醒，通知权限规则规则优化、规则优化(使用quickFind)

- src/apps/com.shanghaionstar.ts
> feat(安吉星): 开屏广告

- src/apps/com.cyl.musiccy.ou.ts
- 【开屏广告】- 规则优化
- 【插屏广告】- 规则优化
#1345
> feat(OMOFUN): 规则优化

- src/apps/com.youloft.icloser.ts
> feat(心动日常): 开屏广告规则优化、购买会员-弹窗广告(gkd-kit#1326)

- src/apps/com.ss.android.ugc.aweme.lite.ts
> feat(抖音极速版): 【青少年弹窗】

- src/apps/com.ss.android.article.lite.ts
> feat(头条搜索极速版): 【开屏广告】

- src/apps/com.tencent.mobileqq.ts
> feat(QQ): 开屏广告

- src/apps/com.chipsea.btcontrol.ts
> feat(OKOK): 开屏广告

- src/apps/com.tencent.qqmusic.ts
> feat(QQ音乐): 【首页-底部广告弹窗】

- src/apps/com.baidu.tieba.ts
> feat(百度贴吧): 【首页-悬浮小广告】

- src/apps/com.bilibili.app.in.ts
> feat(bilibili): 【评论区-满意度评价】

- src/apps/com.hihonor.appmarket.ts
- 【开屏广告】
- 【广告弹窗】
- 【悬浮窗小广告】
- 【推送通知】
#1376
> feat(荣耀应用市场)

- src/apps/com.tmall.wireless.ts
> feat(手机天猫)

- src/apps/com.wzwh.bzpaipan.ts
> feat(问真八字排盘)

- src/apps/com.tencent.tgclub.ts
> feat(心悦俱乐部): 开屏广告

- src/apps/com.jingdong.app.mall.ts
> feat(京东): 首页-浮层广告规则优化、首页-弹窗广告

- src/apps/com.thestore.main.ts
促销弹窗默认关闭
https://github.com/gkd-kit/subscription/issues/1402
> feat(1号会员店): 开屏广告, 促销弹窗

- src/apps/tv.danmaku.bilibilihd.ts
https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/142
> feat(哔哩哔哩HD) 青少年模式弹窗

- src/apps/com.bytxmt.banyuetan.ts
https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/143
> feat(半月谈) 开屏广告

- src/apps/com.hihonor.appmarket.ts
> feat(荣耀应用市场):广告弹窗-规则优化

- src/apps/com.baidu.tieba.ts
> feat(百度贴吧): 开屏广告;应用内广告弹窗

- src/apps/cn.com.yunma.school.app.ts
> feat(易校园): 开屏广告

- src/apps/com.firebear.androil.ts
> feat(小熊油耗): 广告弹窗

- src/apps/com.sankuai.meituan.takeoutnew.ts
> feat(美团外卖): 付款后广告弹窗

- src/apps/org.gushiwen.gushiwen.ts
> feat(古诗文网): 应用内广告弹窗规则优化(gkd-kit#1404)

- src/apps/com.jsguohua.youquanmall.tt.ts
https://github.com/gkd-kit/subscription/issues/1401
> feat(图图影视): 开屏, 弹窗

- src/apps/com.wacai365.ts
> feat(挖财记账)

- src/apps/com.bilibili.app.in.ts
https://github.com/gkd-kit/subscription/issues/1443
> feat(bilibili): App评价弹窗

- src/apps/com.eg.android.AlipayGphone.ts
更新url和ActivityId
https://github.com/gkd-kit/subscription/issues/1446
> feat(花呗): 升级弹窗ActivityId

- src/apps/cn.com.open.mooc.ts
> feat(慕课网): 开屏广告-10周年活动

- src/apps/com.sfacg.ts
https://github.com/gkd-kit/subscription/issues/1450
> feat(菠萝包轻小说): 开屏广告

- src/apps/com.magicalstory.AppStore.ts
https://github.com/gkd-kit/subscription/issues/1451
> feat(奇妙应用): 开屏广告, 下方横幅

- src/apps/com.lofter.android.ts
> feat(LOFTER): 开屏广告

- src/apps/com.yiban.app.ts
> feat(易班):开屏广告

- src/apps/com.cgbchina.xpt.ts
> feat(广发银行):开屏广告

- src/apps/com.jingdong.app.mall.ts
> feat(京东):支付界面-产品推荐

- src/apps/com.dragon.read.ts
> feat(番茄免费小说): 关闭阅读-全屏广告

- src/apps/com.lucky.luckyclient.ts
https://github.com/gkd-kit/subscription/issues/1406
> feat(瑞幸咖啡): 优惠卷返回

- src/apps/com.ximalaya.ting.android.ts
> feat(喜马拉雅): 我的-中间卡片式广告

- src/apps/com.qq.reader.ts
> feat(QQ阅读): 青少年弹窗

- src/apps/com.wacai365.ts
> feat(挖财记账): 开屏广告

- src/apps/com.sina.weibo.ts
> feat(微博): 开屏广告

- src/apps/com.eg.android.AlipayGphone.ts
- 【关闭开启定位提示】- 规则优化
- 【关闭开启通知提示】#1497
> feat(支付宝):关闭开启通知提示

- src/apps/com.coloros.phonemanager.ts
> feat(OPPO手机管家): 版本更新

- src/apps/com.qq.ac.android.ts
https://github.com/gkd-kit/subscription/issues/1505
> feat(腾讯动漫): 两个新的ActivityId

- src/apps/com.xingin.xhs.ts
> feat(小红书):申请开启通知

- src/apps/cn.soulapp.android.ts
> Fix(Soul):开屏广告

- src/apps/com.google.android.apps.youtube.music.ts
https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/145
> feat(YouTube Music) 播放界面广告

- src/apps/com.android.browser.ts
> feat(小米浏览器):主页信息流广告-规则优化

- src/apps/com.android.bankabc.ts
> feat(中国农业银行):开屏广告跳过优化

- src/apps/com.MobileTicket.ts
> feat(铁路12306):开屏广告跳过优化

- src/apps/com.svm.hbyy.ts
https://github.com/gkd-kit/subscription/issues/1527
> feat(比翼多开): 开屏广告, 弹窗广告

- src/apps/com.oray.sunlogin.ts
https://github.com/gkd-kit/subscription/issues/1539
> fix(向日葵远程控制): 解决误触问题

- src/apps/com.hypergryph.skland.ts
> feat(森空岛): 青少年模式弹窗

- src/apps/com.ikang.official.ts
> feat(爱康约体检查报告): 开屏广告

- src/apps/com.shark.jizhang.ts
https://github.com/gkd-kit/subscription/issues/1480
> feat(鲨鱼记账): 开屏广告

- src/apps/com.xiaomi.market.ts
- 应用升级界面-顶部广告横幅
- 请求开启推送弹窗
- 规则优化(使用quickFind)
> feat(小米应用商店): 一些规则优化

- src/apps/com.chaoxing.mobile.ts
> feat(学习通): 开启消息通知、规则优化(使用quickFind)

- src/apps/com.xtc.watch.ts
> feat(小天才): 弹窗提醒、开启通知提醒规则优化

- src/apps/com.taobao.taobao.ts
> feat(淘宝):菜鸟页面-下次从首页找到

- src/apps/com.zhihu.android.ts
- 【回答底部评论顶部的任意广告推荐】-规则优化 #1533
> Fix(知乎):回答底部评论顶部的任意广告推荐

- src/apps/com.netease.cloudmusic.ts
> feat(网易云音乐):版本更新

- src/apps/com.xyhui.ts
> feat(PU口袋校园): 开屏广告规则优化、我的-弹窗广告

- src/apps/com.csair.mbp.ts
> feat(南方航空): 首页-弹窗广告

- src/apps/cn.com.yunma.school.app.ts
> feat(易校园): 开屏广告规则优化(gkd-kit#1442)

- src/apps/com.taobao.taobao.ts
- 限时福利弹窗规则优化(#1444)
- 开启系统通知提示(#1502)
- 消息页面-热门活动卡片规则优化(#1567)
- 各级页面-添加到首页弹窗
> feat(淘宝): 一些优化、新增规则

- src/apps/com.UCMobile.ts
> feat(UC浏览器): 开屏广告

- src/apps/com.android.mediacenter.ts
> Fix(华为音乐):开屏广告

- src/apps/com.tencent.qqmusic.ts
> feat(QQ音乐):中部弹窗

- src/apps/com.bbk.appstore.ts
> feat(vivo应用商店): 请求消息通知

- src/apps/com.kkeji.news.client.ts
https://github.com/gkd-kit/subscription/issues/1577
> feat(快科技): 开屏广告

- src/apps/com.terminus.tmall.ts
https://github.com/gkd-kit/subscription/issues/1570
> feat(金币云商): 开屏广告

- src/apps/com.taobao.taobao.ts
https://github.com/gkd-kit/subscription/issues/1582
> feat(淘宝): 升级弹窗新ActivityIds

- src/apps/com.xuexiaoyi.xxy.ts
#1336 
- 开屏广告规则优化
- 升级弹窗
- 首页-底部广告
> feat(学小易): 开屏广告规则优化、升级弹窗、首页-底部广告(gkd-kit#1336)

- src/apps/com.heytap.browser.ts
> feat(OPPO浏览器):开屏广告

- src/apps/com.sina.weibo.ts
- 右下角悬浮广告（完善规则）
- 评论区博主内容推荐（切换点击目标，防止误触点赞列表）
> feat&fix(微博) 右下角悬浮广告（完善规则）、评论区博主内容推荐（切换点击目标，防止误触点赞列表）

- src/apps/me.ele.ts
> feat(饿了么): 开屏广告、付款后广告弹窗

- src/apps/com.netease.cloudmusic.ts
> feat(网易云音乐):播放界面右上角-免费听歌

- src/apps/com.dubox.drive.ts
> feat(TeraBox): 开屏广告、广告弹窗

- src/apps/com.dragon.read.ts
https://github.com/gkd-kit/subscription/issues/1621
> feat(番茄免费小说): 开屏广告

- src/apps/com.oppo.market.ts
> 一加软件商店开屏广告

- src/apps/tv.danmaku.bili.ts
https://github.com/gkd-kit/subscription/issues/1629
> feat(哔哩哔哩	): 忽略自动更新

- src/apps/com.viva.note.ts
https://github.com/gkd-kit/subscription/issues/970
> feat(囧次元): 应用内弹窗

- src/apps/com.sgcc.evs.echarge.ts
> feat(e充电): 开屏广告

- src/apps/com.huawei.health.ts
> feat(华为运动健康):开屏广告

- src/apps/com.ss.android.ugc.aweme.ts
https://github.com/gkd-kit/subscription/issues/1651
> feat(抖音): 开屏广告

- src/apps/com.qihoo.srouter.n300.ts
https://github.com/gkd-kit/subscription/issues/1653
> feat(360家庭防火墙): 开屏广告

- src/apps/me.piebridge.brevent.ts
黑阈会弹出权限不足的弹窗，在oppo等设备上不想取消系统的权限监控，就需要自动点取消
> feat(黑阈): 权限不足取消

- src/apps/com.google.android.apps.photos.ts
> feat(谷歌相册): 谷歌相册取消更新

- src/apps/com.instagram.android.ts
https://github.com/gkd-kit/subscription/issues/1287
https://github.com/gkd-kit/subscription/issues/702
https://github.com/gkd-kit/subscription/issues/1295
默认关闭.
为了关广告要点太多步骤了, 还不如就忍着
> feat(Instagram): 信息流广告

- src/apps/com.android.thememanager.ts
> feat(miui主题壁纸):广告弹窗

- src/apps/android.zhibo8.ts
https://github.com/gkd-kit/subscription/issues/1656
> fix(直播吧): 信息流不工作 & 开屏优化

- src/apps/com.manmanbuy.bijia.ts
https://github.com/gkd-kit/subscription/issues/1644
> feat(慢慢买): 开屏广告

- src/apps/com.baidu.tieba.ts
https://github.com/gkd-kit/subscription/issues/1546
> fix(百度贴吧): 误触修复

- src/apps/com.hypergryph.skland.ts
> fix(森空岛): 误触修复

- src/apps/com.fanli.android.apps.ts
> feat(返利): 开屏广告

- src/apps/com.chinamobile.hycloudphone.ts
> feat(移动云手机):开屏广告

- src/apps/tv.tvguo.androidphone.ts
> feat(电视果):开屏广告

- src/apps/com.zhouyu.music.ts
https://github.com/gkd-kit/subscription/issues/1682#issuecomment-1788907051
> feat(微音乐): 弹窗广告

- src/apps/com.samsung.android.packageinstaller.ts
https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/146
> feat(软件包安装程序) 请求开启反恶意软件提示弹窗

- src/apps/com.wm.dmall.ts
https://github.com/gkd-kit/subscription/issues/1746
> feat(多点): 更新提示

- src/apps/com.ss.android.ugc.aweme.ts
> feat(抖音):休息提醒

- src/apps/com.mt.mtxx.mtxx.ts
> feat(美图秀秀):版本更新

- src/apps/com.netease.cloudmusic.ts
- 【广告卡片】-规则优化 #1756 
- 【VIP弹窗】 #1735 #1736 
@lisonge 
为什么`preKeys: 1,`也有反应，不应该是`preKeys: 0,`吗
key: 0,
activityIds: [
'com.netease.cloudmusic.activity.MainActivity',
'com.netease.cloudmusic.music.biz.comment.activity.CommentActivity',
'com.netease.cloudmusic.music.biz.comment.activity.ReplyCommentActivity2',
'com.netease.cloudmusic.music.biz.search.activity.SearchActivity',
],
matches: '[id="com.netease.cloudmusic:id/adTagClose"]',
snapshotUrls: [
'https://i.gkd.li/import/12829944',
'https://gkd-kit.gitee.io/import/12723229',
'https://gkd-kit.gitee.io/import/12829938',
'https://gkd-kit.gitee.io/import/12829964',
'https://gkd-kit.gitee.io/import/12829953',
],
},
{
preKeys: 1,
matches: '[text="直接关闭"]',
snapshotUrls: ['https://i.gkd.li/import/12829967'],
}, …
> feat(网易云音乐): 广告卡片、VIP弹窗

- src/apps/com.shaoniandream.ts
> feat(少年梦阅读):开屏广告

- src/apps/com.sgcc.wsgw.cn.ts
> feat(网上国网):开屏广告

- src/apps/com.fanli.android.apps.ts
https://github.com/gkd-kit/subscription/issues/1775
> feat(返利): 应用内弹窗

- src/apps/com.zhouyu.music.ts
https://github.com/gkd-kit/subscription/issues/1774
> feat(微音乐): 搜索底部广告

- src/apps/com.fenbi.android.solar.ts
https://github.com/gkd-kit/subscription/issues/1779
> feat(小猿搜题): 升级提示

- src/apps/com.coolapk.market.ts
- src/apps/com.sgcc.wsgw.cn.ts
https://github.com/gkd-kit/subscription/issues/1783
> feat(网上国网): 弹窗, 开屏

- src/apps/com.tencent.androidqqmail.ts
https://github.com/gkd-kit/subscription/issues/1776
> fix(QQ邮箱): 二次点击失效

- src/apps/com.ximalaya.ting.android.ts
> feat(喜马拉雅):首页-专辑订阅推荐弹窗

- src/apps/com.videogo.ts
> feat(萤石云视频): 首页广告

- src/apps/com.tencent.androidqqmail.ts
https://github.com/gkd-kit/subscription/issues/1776
其实我不太明白是怎么从英文版到中文版的.
> feat(QQ邮箱): 不感兴趣

- src/apps/com.google.android.gm.ts
> feat(Gmail): 信息流广告

- src/apps/com.duokan.reader.ts
> feat(多看):首页-广告弹窗

- src/apps/tv.danmaku.bili.ts
> feat(哔哩哔哩):推荐-信息流广告

- src/apps/com.zhl.bmi.ts
> feat(乐看视频):推荐-广告弹窗

- src/apps/cn.wps.moffice_eng.ts
> feat(WPS): 首页-文档列表广告、首页-弹窗广告规则优化
