src/apps/com.xyhui.ts
=> feat(PU口袋校园): 首页-弹窗广告、我的-弹窗广告规则优化

src/apps/com.jingdong.app.mall.ts
=> feat(京东): 广告弹窗规则优化、首页-底部横幅广告

src/apps/com.taptap.ts
https://github.com/gkd-kit/subscription/issues/1844
=> fix(TAPTAP): 增加acid

src/apps/com.vivo.wallet.ts
https://github.com/gkd-kit/subscription/issues/1674
=> feat(VIVO钱包): 开屏广告

src/apps/com.ximalaya.ting.android.ts
=> feat(喜马拉雅):首页-推荐列表广告

src/apps/com.huawei.music.ts
https://github.com/gkd-kit/subscription/issues/1886
=> fix(华为音乐): 误触修复

src/apps/com.ximalaya.ting.android.ts
https://github.com/gkd-kit/subscription/issues/1911
=> feat(喜马拉雅): 二步确认

src/apps/com.klcxkj.zqxy.ts
https://github.com/gkd-kit/subscription/issues/1898
=> feat(趣智校园): 弹窗

src/apps/org.gushiwen.gushiwen.ts
https://github.com/gkd-kit/subscription/issues/1899
=> feat(古诗文网): 弹窗

src/apps/com.ruanmei.zuihuimai.ts
https://github.com/gkd-kit/subscription/issues/1900
=> feat(最会买): 开屏

src/apps/com.chinarainbow.tft.ts
https://github.com/gkd-kit/subscription/issues/1902
=> feat(天府通): 弹窗

src/apps/com.ss.android.article.news.ts
https://github.com/gkd-kit/subscription/issues/1903
=> feat(今日头条): 视频页浮窗

src/apps/com.chunqiu.ah.ts
https://github.com/gkd-kit/subscription/issues/1892
=> feat(AH视频): 开屏, 弹窗

src/apps/io.sbyd.app.ts
https://github.com/gkd-kit/subscription/issues/1835
=> feat(轻松阅): 开屏, 弹窗

src/apps/com.jincheng.supercaculator.ts
https://github.com/gkd-kit/subscription/issues/1834
=> feat(全能计算器): 京东弹窗

src/apps/com.tencent.tmgp.kgame.ppcr.ts
https://github.com/gkd-kit/subscription/issues/1920
=> feat(全民泡泡超人): 开屏广告

src/apps/com.dingda.app.ts
https://github.com/gkd-kit/subscription/issues/1919
=> feat(叮嗒出行): 开屏广告

src/apps/com.vphonegaga.titan.ts
=> feat(光速虚拟机): 开屏广告、广告弹窗

src/apps/com.lptiyu.tanke.ts
https://github.com/gkd-kit/subscription/issues/1897
=> feat(步道乐跑): 开屏广告

src/apps/com.huawei.search.ts
https://github.com/gkd-kit/subscription/issues/1895
=> feat(智慧搜索): 新的id

src/apps/com.weico.international.ts
https://github.com/gkd-kit/subscription/issues/1960
=> feat(微博轻享版): 开屏广告

src/apps/com.miui.player.ts
https://github.com/gkd-kit/subscription/issues/1935
小米音乐
=> feat(音乐): 开屏, 浮窗

src/apps/com.aiwu.market.ts
https://github.com/gkd-kit/subscription/issues/1942
=> feat(爱吾游戏盒子): 开屏广告

src/apps/com.ximalaya.ting.android.ts
https://github.com/gkd-kit/subscription/issues/1953
=> feat(喜马拉雅): 更新activityid

src/apps/com.byfen.market.ts
https://github.com/gkd-kit/subscription/issues/1959
=> feat(百分网游戏盒子): 开屏广告

src/apps/io.sbyd.app.ts
https://github.com/gkd-kit/subscription/issues/1961
=> feat(轻松阅): 弹窗广告

src/apps/gov.pianzong.androidnga.ts
https://github.com/gkd-kit/subscription/issues/1964
=> feat(NGA玩家社区): 调整开屏规则, 新的卡片广告

src/apps/com.tencent.karaoke.ts
https://github.com/gkd-kit/subscription/issues/1962
=> fix(全民K歌): 开屏广告

src/apps/com.miui.securitycenter.ts
https://github.com/gkd-kit/subscription/issues/1901
=> feat(小米安装器): 继续安装

src/apps/com.sankuai.meituan.takeoutnew.ts
https://github.com/gkd-kit/subscription/issues/1915
=> feat(美团外卖): 关闭自动更新

src/apps/com.youxiang.soyoungapp.ts
https://github.com/gkd-kit/subscription/issues/1982
=> feat(新氧医美): 开屏

src/apps/com.google.android.apps.googlevoice.ts
默认关闭
https://github.com/gkd-kit/subscription/issues/1983
=> feat(Google Void): 跳过电话号码链接请求

src/apps/com.tencent.docs.ts
https://github.com/gkd-kit/subscription/issues/1946
不清楚为什么会误触, 从快照上看没有目标, ActivityId也不一样. 加了delay试试看?
=> feat(腾讯文档): 误触?

src/apps/com.ss.android.article.news.ts
=> feat(今日头条):更新弹窗

src/apps/com.cheersedu.app.ts
=> feat(湛庐阅读):开屏广告、版本更新

src/apps/com.ct.client.ts
=> feat(中国电信):首页-取消升级

src/apps/deepal.com.cn.app.ts
=> feat(深蓝汽车):开屏广告

src/apps/com.ximalaya.ting.android.ts
=> feat(喜马拉雅): 播放页面-底部推荐列表-夹杂广告

src/apps/com.huachenjie.shandong_school.ts
https://github.com/gkd-kit/subscription/issues/1694
=> feat(闪动校园): 开屏修复

src/apps/com.pocket.snh48.activity.ts
=> feat(口袋48):开屏广告

src/apps/com.videogo.ts
=> feat(萤石云视频):开屏广告

src/apps/com.jianshu.haruki.ts
=> feat(简书):开屏广告、VIP弹窗

src/apps/com.byd.sea.ts
=> feat(比亚迪海洋):开屏广告

src/apps/com.firebear.androil.ts
=> feat(小熊油耗):广告弹窗

src/apps/com.sinovatech.unicom.ui.ts
=> feat(中国联通):开屏广告

src/apps/com.ddyc.lotterytool.ts
- 【开屏广告】
- 【广告弹窗】
- 【请求推送通知弹窗】
- #2014
=> feat(彩虹多多)

src/apps/com.crland.mixc.ts
=> feat(一点万象):开屏广告

src/apps/com.kugou.android.lite.ts
- 【开屏广告】-规则优化 
- #2012 
- #1993
=> feat(酷狗概念版):开屏广告

src/apps/com.sh.tlzgh.ts
=> feat(上铁职工家园):开屏广告

src/apps/com.baidu.tieba.ts
- 整合  #2040 
- 【吧内-悬浮卡通-进吧逛逛】-规则优化 #1698
=> feat(百度贴吧):规则优化

src/apps/com.immomo.momo.ts
https://github.com/gkd-kit/subscription/issues/2056
=> feat(陌陌): 开屏广告

src/apps/com.dragon.read.ts
https://github.com/gkd-kit/subscription/issues/2006
=> feat(番茄小说): 右侧悬浮窗广告

src/apps/com.jingyao.easybike.ts
https://github.com/gkd-kit/subscription/issues/2062
=> feat(哈喽骑行): 弹窗新的activityIds

src/apps/com.sinovatech.unicom.ui.ts
https://github.com/gkd-kit/subscription/issues/2062
=> feat(中国联通) 权限申请

src/apps/com.wm.dmall.ts
https://github.com/gkd-kit/subscription/issues/2062
默认关闭
=> feat(多点): 优惠券弹窗

src/apps/me.ele.ts
https://github.com/gkd-kit/subscription/issues/2062
=> feat(饿了么): 红包弹窗新的activityIds

src/apps/com.zhihu.android.ts
=> fix(知呼): 关闭误触规则

src/apps/com.haien.app.TrainPassNative.ts
=> feat(铁路人):开屏广告

src/apps/com.jingdong.app.mall.ts
=> feat(京东):广告弹窗

src/apps/com.dfsly.bbs.ts
https://github.com/gkd-kit/subscription/issues/2083
https://github.com/gkd-kit/subscription/issues/2057
=> feat(AC匿名版): 开屏, 弹窗

src/apps/com.coolapk.market.ts
=> fix(酷安): 通知权限

src/apps/com.cmbchina.ccd.pluto.cmbActivity.ts
=> feat(掌上生活):规则优化

src/apps/com.zmzx.college.search.ts
=> feat(大学搜题酱):规则优化

src/apps/io.dcloud.H514D19D6.ts
=> feat(代练通): 开屏广告

src/apps/com.galaxy.stock.ts
=> feat(中国银河证券): 开屏广告

src/apps/com.android.tiancity.mobilesecurity.ts
=> feat(天成账号管家): 开屏广告

src/apps/com.blackbees.xlife.ts
https://github.com/gkd-kit/subscription/issues/2089
=> feat(xlife): 开屏广告

src/apps/com.baidu.newapp.ts
https://github.com/gkd-kit/subscription/issues/2129
=> feat(文心一言): 升级提示

src/apps/com.cmbchina.ccd.pluto.cmbActivity.ts
https://github.com/gkd-kit/subscription/issues/2129
=> feat(掌上生活): 弹窗

src/apps/com.wibo.bigbang.ocr.ts
https://github.com/gkd-kit/subscription/issues/2129
=> feat(布丁扫描): 升级提示

src/apps/com.kmxs.reader.ts
https://github.com/gkd-kit/subscription/issues/2134
=> feat(七猫小说): 弹窗广告

src/apps/com.tadu.read.ts
=> feat(塔读小说免费版):开屏广告

src/apps/com.waimaiii.waimaiii.ts
=> feat(歪麦霸王餐):开屏广告、广告弹窗

src/apps/top.xuante.moloc.ts
=> feat(摩尼定位):开屏广告

src/apps/com.xuexiaoyi.xxy.ts
=> feat(学小易): 开屏广告、首页-底部广告规则优化

src/apps/com.maxhom.weibu.ts
- 交友-底部广告
- 漂流瓶-提示弹窗
- 漂流瓶-定位弹窗
=> feat(暮瑟): 交友-底部广告、漂流瓶-提示弹窗、漂流瓶-定位弹窗

src/apps/com.changba.ts
https://i.gkd.li/import/13373946
=> feat(唱吧): 开屏广告

src/apps/com.codoon.gps.ts
=> feat(咕咚):开屏广告、广告弹窗

src/apps/com.jincheng.supercaculator.ts
=> feat(全能计算器):弹窗广告

src/apps/com.pcs.knowing_weather.ts
=> feat(知天气-决策):版本更新

src/apps/com.excean.gspace.ts
https://github.com/gkd-kit/subscription/issues/2180
=> feat(ourplay): 开屏广告规则优化

src/apps/com.tencent.mobileqq.ts
=> feat(QQ): 消息页面-顶部广告、更新弹窗规则优化

src/apps/com.tencent.mobileqq.ts
=> feat(QQ):好友动态-为你推荐

src/apps/cn.xiaochuankeji.zuiyouLite.ts
=> feat(皮皮搞笑):信息流广告

src/apps/com.chinatelecom.bestpayclient.ts
=> feat(翼支付):版本更新

src/apps/com.bilibili.app.in.ts
=> feat(bilibili):订阅感兴趣的通知

src/apps/com.duowan.kiwi.ts
=> feat(虎牙直播):直播间悬浮广告

src/apps/com.shct.yi.ts
=> feat(电信云宽带):开屏广告

src/apps/com.cn21.ecloud.ts
=> feat(天翼云盘):版本更新

src/apps/com.tencent.map.ts
=> feat(腾讯地图):开屏广告

src/apps/com.atour.atourlife.ts
=> feat(亚朵):开屏广告

src/apps/com.huawei.hwread.dz.ts
=> feat(华为阅读):开屏广告

src/apps/com.lenovo.browser.hd.ts
- https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/161
=> feat(联想浏览器HD) 更新弹窗、请求通知权限弹窗

src/apps/com.lenovo.leos.appstore.ts
- https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/issues/160
=> feat(联想应用中心) 更新弹窗、请求通知权限弹窗

src/apps/com.douban.frodo.ts
- 合并key 10、13 【弹窗广告】
- 合并key 11、12 【版本更新】
- 整理key 3 【信息流广告】
- 整理优化key 8 【帖子内容与评论区中间的卡片式广告】
=> feat(豆瓣):规则优化

src/apps/org.daimhim.zzzfun.ts
=> feat(ZzzFun):开屏广告、广告弹窗

src/apps/com.pandabus.android.zb.ts
=> feat(淄博出行):广告弹窗

src/apps/com.jingyao.easybike.ts
=> feat(哈啰):请求通知权限弹窗

src/apps/com.chinatelecom.bestpayclient.ts
=> feat(翼支付):广告弹窗、悬浮窗小广告

src/apps/com.cmbchina.ccd.pluto.cmbActivity.ts
=> feat(掌上生活):右侧悬浮广告

src/apps/com.android.bbkmusic.ts
https://github.com/gkd-kit/subscription/issues/2241
=> feat(i 音乐): 开屏广告

src/apps/com.dragon.read.ts
https://github.com/gkd-kit/subscription/issues/2233
=> feat(番茄免费小说): 关闭阅读中作者窗口

src/apps/com.taptap.ts
https://github.com/gkd-kit/subscription/issues/2189
=> feat(taptap): 更新弹窗

src/apps/com.aiwu.market.ts
https://github.com/gkd-kit/subscription/issues/2190
=> feat(爱吾游戏宝盒): 开屏广告逻辑更改

src/apps/com.nowcasting.activity.ts
https://github.com/gkd-kit/subscription/issues/2183
=> feat(彩云天气): VIP弹窗, 广告弹窗

src/apps/com.cctv.cctv5ultimate.ts
https://github.com/gkd-kit/subscription/issues/2188
=> feat(央视体育): 开屏, 弹窗

src/apps/com.wandafilm.app.ts
=> feat(万达电影):开屏广告

src/apps/yesoul.yesoulmobile.ts
=> feat(Yesoul):开屏广告

src/apps/com.hujiang.cctalk.ts
=> feat(CCtalk):开屏广告

src/apps/com.citymobi.fufu.ts
=> feat(服服):开屏广告

src/apps/com.huicent.ts
=> feat(山航掌尚飞):开屏广告

src/apps/com.midea.vm.washer.ts
=> feat(U净):开屏广告

src/apps/cn.beekee.zhongtong.ts
=> feat(中通快递):开屏广告

src/apps/net.huanci.hsjpro.ts
=> feat(画世界Pro):开屏广告

src/apps/com.hualu.heb.zhidabus.ts
=> feat(哈尔滨交通出行):开屏广告

src/apps/com.hanweb.android.sdzwfw.activity.ts
=> feat(爱山东):开屏广告

src/apps/com.tencent.mm.ts
=> feat(微信):微信小程序-开屏广告

src/apps/com.naver.linewebtoon.cn.ts
=> feat(咚漫漫画):开屏广告

src/apps/me.ele.ts
=> feat(饿了么):版本更新

src/apps/com.duowan.kiwi.ts
=> feat(虎牙直播):直播间底部弹窗

src/apps/com.miui.fm.ts
https://github.com/gkd-kit/subscription/issues/2320
=> feat(蜻蜓FM): 开屏广告

src/apps/com.seebaby.ts
https://github.com/gkd-kit/subscription/issues/2327
=> feat(掌通家园): 开屏广告

src/apps/com.duowan.kiwi.ts
https://github.com/gkd-kit/subscription/issues/2325
=> feat(虎牙): 直播间弹窗

src/apps/com.max.xiaoheihe.ts
https://github.com/gkd-kit/subscription/issues/2329
=> feat(小黑盒): 签到确认 

src/apps/com.buyanchuantong.buyanshufa.ts
=> feat(不厌书法):功能介绍

src/apps/com.cyl.musiccy.ou.ts
- 整合优化key0【开屏广告】
- 整合优化key2【插屏广告】
- #2253 
- #2326
=> feat(OMOFUN):规则优化

src/apps/com.picacomic.fregata.ts
1. 开屏广告
2. 主界面公告
3. 漫画页卡片广告
4. 点击签到和确认
=> feat(PicACG):广告

src/apps/com.cmbchina.ccd.pluto.cmbActivity.ts
=> feat(掌上生活):activityIds写法优化

src/apps/com.zivn.cloudbrush3.ts
=> feat(书法字典大全):信息流广告

src/apps/com.ants360.yicamera.ts
=> feat(小蚁摄像机):开屏广告

src/apps/com.skyplatanus.crucio.ts
=> feat(快点阅读):开屏广告

src/apps/com.chinarailway.globalticketing.ts
https://github.com/gkd-kit/subscription/issues/2373
=> feat(铁路12306 play版): 开屏广告

src/apps/uni.UNIE7FC6F0.ts
=> feat(MERIT超燃脂):开屏广告

src/apps/com.service.android.gov.cn.ts
=> feat(国家政务服务平台):开屏广告

src/apps/com.taobao.movie.android.ts
=> feat(淘票票):开屏广告

src/apps/com.qiekj.user.ts
=> feat(胖乖生活): 更新弹窗

src/apps/com.alibaba.android.rimet.ts
=> feat(钉钉): 电脑钉钉自动登录

src/apps/com.sina.oasis.ts
=> feat(绿洲): 开屏广告及首页-推荐广告

src/apps/com.sohu.sohuvideo.ts
=> feat(搜狐视频):开屏广告、版本更新

src/apps/com.magicalstory.AppStore.ts
=> feat(奇妙应用): 公告弹窗

src/apps/com.bbk.theme.ts
=> feat(i主题): 开屏广告

src/apps/com.dangdang.buy2.ts
=> feat(当当):开屏广告

src/apps/com.hpbr.bosszhipin.ts
=> feat(BOSS直聘): 通知权限授权弹窗

src/apps/com.duowan.kiwi.ts
=> feat(虎牙直播): 更新弹窗（默认关闭）

src/apps/com.vivo.wallet.ts
=> feat(钱包): 自动禁止通知权限授权（默认关闭）

src/apps/com.zmzx.college.search.ts
=> feat(大学搜题酱): 禁止开启推送通知（默认关闭）

src/apps/com.huawei.appmarket.ts
https://github.com/gkd-kit/subscription/issues/2417
=> feat(华为应用市场): 更新提示(兼容所有华为系统应用)

src/apps/com.huawei.wallet.ts
https://github.com/gkd-kit/subscription/issues/2418
=> feat(华为钱包): 完整服务横幅提示

src/apps/com.bocop.cbsp.ts
https://github.com/gkd-kit/subscription/issues/2419
=> feat(中银跨境GO): 开屏广告

src/apps/com.simplesecurity.english.ts
=> feat(水果派):开屏广告 

src/apps/com.excean.gspace.ts
=> feat(OurPlay):弹窗广告

src/apps/com.taobao.taobao.ts
=> feat(淘宝):开启系统通知提示

src/apps/com.dataoke.union.ts
=> feat(大淘客联盟):开启消息通知

src/apps/client.android.yixiaotong.ts
=> feat(乐校通):底部卡片广告

src/apps/com.catlinks.app.ts
=> feat(CATLINK):开屏广告

src/apps/com.jv.samsungeshop.ts
=> feat(三星商城):开屏广告

src/apps/fit.flutter.dsm_helper.ts
=> feat(群晖助手):开屏广告

src/apps/com.magicalstory.AppStore.ts
=> feat(奇妙应用):卡片式广告

src/apps/com.sohu.sohuvideo.ts
=> feat(搜狐视频):青少年模式

src/apps/com.tencent.weishi.ts
=> feat(微视):青少年模式

src/apps/cn.emagsoftware.gamehall.ts
=> feat(咪咕快游):版本更新

src/apps/cmccwm.mobilemusic.ts
=> feat(咪咕音乐):版本更新

src/apps/tv.danmaku.bili.ts
=> feat(哔哩哔哩):个性化内容推荐弹窗

src/apps/com.xunlei.downloadprovider.ts
=> feat(迅雷):会员续费广告

src/apps/com.sankuai.movie.ts
=> fix(猫眼):开屏广告

src/apps/com.xingin.xhs.ts
=> feat(小红书):信息流广告

src/apps/com.yunxiang.wuyu.ts
=> feat(特狗APP):开屏广告、公告弹窗、广告弹窗

src/apps/com.chinatelecom.bestpayclient.ts
=> feat(翼支付):广告弹窗

src/apps/com.heytap.market.ts
=> feat(OPPO软件商店):版本更新

src/apps/com.ss.android.article.video.ts
=> fix(西瓜视频):通知弹窗

src/apps/com.maxhom.weibu.ts
=> feat(暮瑟): 漂流瓶-提示弹窗、漂流瓶-定位弹窗规则优化

src/apps/com.xuexiaoyi.xxy.ts
=> feat(学小易): 首页-底部广告规则优化

src/apps/cn.com.spdb.mobilebank.per.ts
=> feat(浦发银行): 消息中心-系统通知请求

src/apps/com.xyhui.ts
=> feat(PU口袋校园): 开屏广告、弹窗广告规则优化

src/apps/com.able.wisdomtree.ts
=> feat(知到): 升级提醒

src/apps/com.cloudy.component.ts
=> feat(广汽传祺): 开屏广告

src/apps/com.ss.android.article.news.ts
=> feat(今日头条):更新弹窗跳过优化

src/apps/com.kmxs.reader.ts
=> feat(七猫免费小说): 【字节】视频广告（默认关闭）

src/apps/com.ants360.yicamera.ts
=> feat(小蚁摄像机): 弹窗广告

src/apps/com.ygkj.chelaile.standard.ts
=> feat(车来了):应用内广告卡片

src/apps/com.douban.frodo.ts
=> feat(豆瓣):不分享/同步作品短评

src/apps/com.qingdaonews.bus.ts
=> feat(青岛公交查询): 开屏广告

src/apps/com.samsung.android.packageinstaller.ts
https://github.com/gkd-kit/subscription/issues/2307
=> feat(三星安装程序界面): 取消打开反恶意软件

src/apps/com.qidian.QDReader.ts
https://github.com/gkd-kit/subscription/issues/2548
=> feat(起点): 弹窗新activityIds

src/apps/com.vidure.papago.ts
=> feat(PAPAGO焦点):开屏广告

src/apps/cc.kinva.smartqa.ts
=> feat(挑战答题助手):开屏广告

src/apps/com.kugou.android.ts
=> feat(酷狗音乐):开屏广告

src/apps/com.cebbank.mobile.cemb.ts
=> feat(光大银行):开屏广告、首页弹窗广告

src/apps/com.kmxs.reader.ts
=> feat(七猫免费小说):百度、腾讯广告

src/apps/com.miui.securitycenter.ts
=> feat(小米手机管家):禁止获取定位、忽略体检分数

src/apps/com.zl.fqbao.ts
=> feat(招联金融):开屏广告

src/apps/com.shizhuang.duapp.ts
=> feat(得物):截屏分享

src/apps/com.autonavi.minimap.ts
=> feat(高德地图):截屏分享

src/apps/com.dataoke.union.ts
=> Fix(大淘客联盟):开启消息通知

src/apps/com.ehai.ts, src/apps/com.vidure.papago.ts
=> feat(一嗨租车):开屏广告

src/apps/com.sina.weibo.ts
- 删除无用且无快照佐证的key1、key2
- 优化key6 【评论区博主内容推荐】
- 新增key15 【评论区底部关注推荐】
- 新增key16 【评论区底部转发推荐】
- #2601
=> feat(微博):规则优化

src/apps/com.doc360.client.ts
=> feat(个人图书馆):开屏广告、阅读-推荐-信息流广告

src/apps/com.chinarainbow.tft.ts
https://github.com/gkd-kit/subscription/issues/2549
=> feat(天府通): 弹窗广告

src/apps/com.taptap.ts
=> feat(TapTap):版本更新

src/apps/com.pleasure.trace_wechat.ts
=> feat(微拾):我的-卡片式广告、【字节】广告弹窗

src/apps/com.eg.android.AlipayGphone.ts
=> feat(支付宝):版本更新

src/apps/com.miui.player.ts
=> feat(小米音乐):开屏广告-规则优化

src/apps/com.klcxkj.zqxy.ts
https://github.com/gkd-kit/subscription/issues/2614
=> feat(趣智校园): 弹窗, 横幅

src/apps/com.mm.android.lc.ts
https://github.com/gkd-kit/subscription/issues/2629
=> feat(乐橙): 开屏广告

src/apps/com.skyworthdigital.picamera.ts
=> feat(创维智慧云):开屏广告

src/apps/com.bilibili.studio.ts
=> feat(必剪):版本更新

src/apps/com.black.unique.ts
=> feat(全球购骑士特权) 开屏广告和主页弹窗

src/apps/com.google.android.apps.translate.ts
=> feat(Google翻译): 登录弹窗

src/apps/com.youloft.calendar.ts
=> feat(万年历):开屏广告

src/apps/com.tipsoon.android.ts
=> feat(简讯):开屏广告

src/apps/com.youku.phone.ts
=> feat(优酷视频):青少年模式弹窗

src/apps/com.baidu.tieba.ts
key10 【悬浮小广告】：matchDelay应该是500，多写了一个0
=> Fix(百度贴吧):悬浮小广告-matchDelay错误

src/apps/com.sgcc.wsgw.cn.ts
=> feat(网上国网):版本更新

src/apps/com.hundsun.winner.pazq.ts
https://github.com/gkd-kit/subscription/issues/2677
=> feat(平安证券): 开屏广告

src/apps/com.xxx.svideo.ts
=> feat(BaseLibrary):开屏广告

src/apps/cn.xiaochuankeji.zuiyouLite.ts
=> feat(皮皮搞笑):开屏广告、青少年模式

src/apps/com.wenhua.bamboo.ts
=> feat(随身行):开屏广告

src/apps/com.vo.icea.ts
=> feat(飞韵听书):开屏广告、播放界面卡片式广告、首页广告弹窗

src/apps/com.zhangkongapp.joke.bamenshenqi.ts
=> feat(八门神器):开屏广告

src/apps/com.github.eprendre.tingshu.ts
=> feat(我的听书):卡片式广告

src/apps/com.qihoo.smart.ts
=> feat(360智慧生活):开屏广告

src/apps/cn.wps.yun.ts
https://github.com/gkd-kit/subscription/issues/2628
=> feat(金山文档): 列表内广告

src/apps/com.kmxs.reader.ts
=> feat(七猫免费小说): 书架顶部广告

src/apps/com.duokan.reader.ts
=> update(多看阅读): 小说页下方广告和全屏广告

src/apps/com.miui.packageinstaller.ts
=> Update (应用包管理组件) 更新安装完成后自动点击完成按钮

src/apps/com.sina.oasis.ts
=> feat(绿洲):首页-推荐广告

src/apps/cn.wps.moffice_eng.ts
https://github.com/gkd-kit/subscription/issues/2693
=> feat(wps): 文档结尾广告

src/apps/com.ichangtou.ts
https://github.com/gkd-kit/subscription/issues/2695
=> feat(长投学堂): 开屏广告

src/apps/com.hcrs.ts
https://github.com/gkd-kit/subscription/issues/2696
=> feat(华彩人生): 开屏广告

src/apps/com.duokan.reader.ts
https://github.com/gkd-kit/subscription/issues/2705
@lisonge 这个改动思路是否正确? 目的: 在key: 0的时候考虑activityIds, 之后preKeys: 0的步骤不再考虑activityIds
=> feat(多看): 全屏广告二步关闭

src/apps/cn.com.gzbank.mbank.ts
=> feat(广银信用卡):开屏广告

src/apps/com.tencent.qqlive.ts
=> feat(腾讯视频): 全屏广告优化

src/apps/com.netease.cloudmusic.ts
=> feat(网易云音乐):卡片式广告、播放界面广告

src/apps/com.luna.music.ts
=> feat(汽水音乐):规则优化

src/apps/tv.danmaku.bili.ts
=> feat(哔哩哔哩):视频悬浮广告

src/apps/com.eco.global.app.ts
=> feat(ECOVACS HOME):开屏广告

src/apps/com.ss.android.auto.ts
- 【首页推荐卡片广告】-新增规则 #2791 
- 整合 #2701
=> feat(懂车帝):首页推荐卡片广告、整合PR

src/apps/com.lws207lws.ts
=> feat(LWSCAM):开屏广告

src/apps/cn.nubia.bbs.ts
=> feat(红魔社区):开屏广告

src/apps/com.hnnx.pmbank.ts
=> feat(河南农信):版本更新

src/apps/com.yitong.bbw.mbank.android.ts
=> feat(广西北部湾银行):开屏广告

src/apps/cn.ccspeed.ts
=> feat(CC加速器): 加速页-分享抽奖浮窗（默认关闭）

src/apps/com.tencent.cmocmna.ts
=> refactor(腾讯手游加速器): 开屏广告

src/apps/com.mm.android.lchg.ts
=> feat(乐橙含光): 升级弹窗（默认关闭）

src/apps/com.youdao.dict.ts
=> feat(网易有道词典): 评价弹窗

src/apps/com.tencent.qt.sns.ts
=> feat(掌上穿越火线): 首页活动弹窗及更新弹窗

src/apps/com.ants360.yicamera.ts
=> feat(小蚁摄像机):弹窗广告

src/apps/com.guodongbaohe.app.ts
=> feat(果冻宝盒): 开屏广告

src/apps/cn.lezhi.speedtest.ts
=> feat(网速管家): 开屏广告

src/apps/com.coloros.gallery3d.ts
https://github.com/gkd-kit/subscription/issues/2851
=> feat(OPPO相册): 更新提示

src/apps/com.qihoo360.antilostwatch.ts
=> feat(360儿童卫士): 开屏广告

src/apps/com.ss.android.ugc.aweme.lite.ts
=> fix(抖音极速版): 新版青少年弹窗失效（补充规则）

src/apps/com.zjwh.android_wh_physicalfitness.ts
=> feat(运动世界校园): 弹窗广告

src/apps/com.miui.player.ts
https://github.com/gkd-kit/subscription/issues/2875
=> feat(小米音乐): 浮窗广告

src/apps/com.guodongbaohe.app.ts
=> feat(果冻宝盒):广告弹窗

src/apps/com.tencent.mm.ts
=> feat(微信):青少年模式弹窗

src/apps/com.mymoney.ts
=> feat(随手记):开屏广告

src/apps/com.gfd.ecprint.ts
=> feat(小白智慧打印):开屏广告

src/apps/com.practical.master.toolsme.ts
=> feat(实用大师):广告弹窗

src/apps/com.nionco.todaysm.ts
=> feat(今日水木): 开屏广告

src/apps/com.nd.android.pandareader.ts
=> feat(熊猫看书):开屏广告

src/apps/cn.paperang.mm.ts
=> feat(喵喵机):开屏广告

src/apps/com.qidian.QDReader.ts
=> feat(起点读书): 福利中心-我知道了

src/apps/com.bwton.tjmetro.ts
=> feat(天津地铁): 开屏广告

src/apps/com.wallstreetcn.news.ts
https://github.com/gkd-kit/subscription/issues/2917
=> fix(华尔街见闻): 开屏广告

src/apps/com.tencent.qt.qtl.ts
=> feat(掌上英雄联盟): 更新弹窗

src/apps/com.alimama.moon.ts
=> feat(淘宝联盟): 开屏广告

src/apps/com.cmstop.shaoxing.ts
=> feat(越牛新闻): 开屏广告

src/apps/com.xiaofeiji.app.disk.ts
=> 小飞机网盘开屏广告Create com.xiaofeiji.app.disk.ts

src/apps/com.miui.player.ts
=> feat(小米音乐):看广告视频领VIP

src/apps/com.able.wisdomtree.ts
=> feat(知到): 消息推送通知

src/apps/com.loyea.adnmb.ts
=> feat(蓝岛): 通知弹窗

src/apps/com.zmzx.college.search.ts
=> feat(大学搜题酱): 升级弹窗

src/apps/com.miui.player.ts
=> feat(小米音乐): 首页-弹窗广告

src/apps/bin.mt.plus.canary.ts
=> feat(MT管理器Pro): 版本更新

src/apps/com.xiaomi.market.ts
=> feat(小米应用商店):个性化推荐弹窗

src/apps/com.sup.android.superb.ts
=> feat(皮皮虾):右上角红包悬浮窗

src/apps/com.sina.weibolite.ts
=> feat(微博极速版):开屏广告

src/apps/com.cloudpower.netsale.activity.ts
=> feat(中国人保):开屏广告

src/apps/com.sina.weibo.ts
=> feat(微博):APP评分弹窗

src/apps/com.jarworld.bleach.bvn.sjm.cyc.ts
=> feat(次元城动漫):开屏广告、广告弹窗

src/apps/com.chinatelecom.bestpayclient.ts
=> feat(翼支付):广告弹窗、年底积分活动弹窗

src/apps/com.netease.cloudmusic.ts
=> feat(网易云音乐):卡片式广告

src/apps/cn.lezhi.speedtest.ts
新增开屏广告-腾讯sdk
删除开屏广告-字节sdk quickFind属性 
- https://github.com/gkd-kit/gkd/issues/369
- #3014
=> feat(网速管家):开屏广告

src/apps/com.smarlife.qingtong.ts
=> feat(清瞳):开屏广告

src/apps/com.mi.health.ts
=> feat(小米运动健康):版本更新

src/apps/com.ss.android.article.video.ts
=> feat(西瓜视频):红包弹窗

src/apps/com.jd.jrapp.ts
=> feat(京东金融):版本更新

src/apps/com.taobao.taobao.ts
=> feat(淘宝):花呗升级报送征信

src/apps/com.enflick.android.TextNow.ts
=> feat(TextNow): 设为默认应用提示

src/apps/com.okii.watch.global.ts
=> feat(小天才): 更新弹窗及手表安全守护弹窗

src/apps/com.android.providers.downloads.ui.ts
=> feat(下载管理): 更新弹窗

src/apps/com.fenbi.android.solar.ts
=> feat(小猿搜题): 开屏广告

src/apps/com.cmi.jegotrip.ts
=> feat(无忧行): 应用内广告弹窗

src/apps/com.unionpay.ts
=> feat(云闪付):规则优化

src/apps/com.taobao.idlefish.ts
=> 增加 自动取消 咸鱼开启手机信息权限弹窗

src/apps/sina.mobile.tianqitong.ts
=> feat(天气通): 开屏广告

src/apps/com.tencent.mobileqq.ts
=> fix(QQ): 扫一扫-登录确认

src/apps/com.gotokeep.keep.ts
=> feat(Keep):开屏广告

src/apps/com.iflytek.inputmethod.ts
=> feat(讯飞输入法):开屏广告

src/apps/com.ss.android.ugc.aweme.lite.ts
=> feat(抖音极速版):朋友推荐弹窗

src/apps/com.jooan.qiaoanzhilian.ts
=> feat(乔安智联):开屏广告

src/apps/com.wisedu.cpdaily.ts
=> feat(今日校园):版本更新

src/apps/cn.etouch.ecalendar.ts
=> feat(中华万年历日历):开屏广告

src/apps/com.duokan.phone.remotecontroller.ts
=> feat(万能遥控):申请定位

src/apps/com.eg.android.AlipayGphone.ts
=> feat(支付宝):关闭花呗升级弹窗

src/apps/com.tencent.southpole.appstore.ts
=> feat(华硕应用市场):开屏广告

src/apps/com.sdjictec.qdmetro.ts
=> feat(青岛地铁):开屏广告

src/apps/com.shangfang.gylm.ts
=> feat(高佣联盟):开屏广告、版本更新

src/apps/com.sfacg.ts
=> feat(菠萝包轻小说):开屏广告

src/apps/com.cib.cibmb.ts
=> feat(兴业银行):开屏广告

src/apps/com.koudai.weidian.buyer.ts
=> feat(微店):首页红包弹窗

src/apps/com.microsoft.emmx.ts
=> feat(Edge):消息通知

src/apps/com.unionpay.ts
=> feat(云闪付):天天签到-获得新勋章提示

src/apps/com.job.android.ts
=> feat(前程无忧51Job):开屏广告

src/apps/com.example.raylink_flutter.ts
=> feat(RayLink):版本更新

src/apps/com.enflick.android.TextNow.ts
=> feat(TextNow):通知/链接蓝牙附件设备 权限申请

src/apps/com.chaozh.iReader.ts
=> feat(VIVO 电子书):开屏广告

src/apps/com.qihoo.camera.ts
=> feat(360摄像机): 卡录像界面广告

src/apps/com.dragon.read.ts
- #2959 
- #3063
- #2931 
- #3182
=> Fix(番茄免费小说):广告弹窗

src/apps/com.coloros.gallery3d.ts
=> feat(相册):开启相册同步弹窗

src/apps/com.jjwxc.reader.ts
https://github.com/gkd-kit/subscription/issues/3161
=> feat(晋江小说阅读):开屏广告

src/apps/com.gvsoft.gofun.ts
https://github.com/gkd-kit/subscription/issues/3163
单看规则不清楚为什么issue里没有执行. 姑且简单改了改.
=> feat(GoFun APP): 开屏, 弹窗

src/apps/com.ss.android.ugc.aweme.ts
=> feat(抖音):请求开启通知提示信息、添加快捷方式到桌面、

src/apps/com.lolaage.tbulu.tools.ts
=> feat(两步路户外助手):弹窗广告

src/apps/com.hupu.shihuo.ts
=> feat(识货):开屏广告

src/apps/net.joydao.radio.ts
=> feat(听听广播):开屏广告

src/apps/com.masadoraandroid.ts
=> fix(魔法集市 Global):开屏广告

src/apps/com.jisu.manhua.ts
https://github.com/gkd-kit/subscription/issues/3212
=> feat(漫画人极速版): 弹窗广告

src/apps/com.dubox.drive.ts
https://github.com/gkd-kit/subscription/issues/3214
https://github.com/gkd-kit/subscription/issues/3213
=> feat(Terabox): 开屏广告, 通知权限

src/apps/com.nowcasting.activity.ts
https://github.com/gkd-kit/subscription/issues/3218
=> feat(彩云天气): 开屏, 插页广告

src/apps/com.ss.android.auto.ts
=> feat(懂车帝):升级弹窗、请求推送通知弹窗、选车页卡片广告

src/apps/com.douban.frodo.ts
=> feat(豆瓣):搜索页/帖子内容与评论区中间的卡片式广告

src/apps/flipboard.cn.ts
https://github.com/gkd-kit/subscription/issues/3244
=> feat(红板报): 开屏广告

src/apps/com.xiaomi.hm.health.ts
=> feat(Zepp Life): 首页-底部广告

src/apps/com.yitong.mbank.psbc.ts
=> feat(邮储银行): 更新弹窗

src/apps/com.xyhui.ts
=> feat(PU口袋校园): 弹窗广告添加activityIds

src/apps/com.rytong.hnair.ts
=> feat(海南航空): 开屏广告

src/apps/com.mfcloudcalculate.networkdisk.ts
=> feat(123云盘):开屏广告

src/apps/com.taobao.taobao.ts
- 版本更新补充activityIds
---
- #3227
- 花呗升级报送征信
=> feat(淘宝): 版本更新补充activityIds;花呗升级报送征信(gkd-kit#3227)

src/apps/com.zuoyebang.knowledge.ts
=> feat(作业帮家长版): 更新提醒

src/apps/com.steampy.app.ts
=> feat(SteamPY):版本更新

src/apps/com.magicalstory.AppStore.ts
=> feat(奇妙应用):搜索页-卡片广告

src/apps/com.xpx365.projphoto.ts
=> feat(工程相机):广告弹窗

src/apps/com.maxhom.weibu.ts
=> feat(暮瑟): 交友-底部广告

src/apps/com.reddit.frontpage.ts
- #3121
- 社区消息-更新提示
- NSFW 内容提示
=> feat(Reddit): 社区消息-更新提示、NSFW 内容提示(gkd-kit#3121)

src/apps/com.twitter.android.ts
- #3191
- 信息流广告-帖子详情页、搜索页 优化规则
=> feat(X): 信息流广告-帖子详情页、搜索页 优化规则(gkd-kit#3191)

src/apps/info.muge.appshare.ts
=> feat(AppShare):开屏广告、下载页-卡片广告

src/apps/com.hupu.shihuo.ts
=> feat(识货):请求消息通知

src/apps/com.moutai.mall.ts
=> feat(i茅台):开屏广告

src/apps/com.hundsun.stockwinner.gszq.ts
=> feat(国盛通):开屏广告

src/apps/com.chenai.eyes.ts
=> feat(夜间模式):全屏广告

src/apps/me.ele.ts
- #3216
- 活动弹窗 规则优化
- 红包弹窗 规则优化
- 开启定位提醒
- 首页-底部浮窗广告
=> feat(饿了么): 规则优化(gkd-kit#3216)

src/apps/com.xiaomi.market.ts
- #3225
- 请求通知权限提示弹窗 补充activityIds
=> feat(小米应用商店): 请求通知权限提示弹窗 补充activityIds(gkd-kit#3225)

src/apps/com.baidu.youavideo.ts
=> feat(一刻相册): 照片-底部浮窗广告(gkd-kit#3224)

src/apps/com.google.android.youtube.ts
- 【视频播放-跳过广告】-新增规则 #3306 
- 删除过时规则属性、快照
=> feat(youtube):视频播放-跳过广告

src/apps/com.hwabao.hbstockwarning.ts
=> feat(华宝智投):开屏广告

src/apps/com.juduoduo.app.ts
=> feat(剧多多):弹窗广告

src/apps/com.klcxkj.zqxy.ts
=> feat(趣智校园):弹窗广告

src/apps/com.when.coco.ts
=> feat(365日历):开屏广告

src/apps/com.android.tnaant.ts
=> feat(蚂蚁加速器):公共弹窗

src/apps/com.tencent.qt.sns.ts
=> feat(掌上穿越火线):更新弹窗

src/apps/com.gwm.tank.ts
=> feat(坦克TANK):开屏广告

src/apps/com.wenshushu.app.android.ts
=> feat(文叔叔):开屏广告

src/apps/com.mihoyo.hyperion.ts
=> 米游社自动打卡规则更新

src/apps/com.tencent.mobileqq.ts
https://github.com/gkd-kit/subscription/issues/3256
=> feat(QQ): 钱包卡片广告

src/apps/com.wwwscn.yuexingbao.ts
=> feat(悦通行):开屏广告

src/apps/com.sdo.sdaccountkey.ts
=> feat(叨鱼):开屏广告

src/apps/com.google.android.gm.ts
=> feat(Gmail): 信息流广告 规则优化(gkd-kit#3343)

src/apps/com.eg.android.AlipayGphone.ts
=> feat(支付宝): 版本更新 规则优化(gkd-kit#2902)

src/apps/com.mxbc.ohsa.ts
=> feat(蜜雪冰城鸿蒙版): 首页-弹窗广告(gkd-kit#3284)

src/apps/com.xiaoenai.app.ts
=> feat(小恩爱):开屏广告、广告弹窗、信息流广告

src/apps/com.sina.weibolite.ts
=> feat(WeiboFast):APP评分

src/apps/com.alibaba.wireless.ts
=> feat(阿里巴巴): 开屏广告 规则优化;首页-弹窗广告(gkd-kit#3199)

src/apps/com.sina.weibolite.ts
=> feat(微博极速版): 信息流广告 规则优化(gkd-kit#3350)

src/apps/com.benqu.wuta.ts
=> feat(无他相机): 开屏广告(gkd-kit#3358)

src/apps/com.zbx.ct.tvzhibo.ts
- #3357
- 弹窗广告
- 浮窗广告
- 播放页面-弹窗广告
=> feat(手机电视高清直播): 弹窗广告、浮窗广告、播放页面-弹窗广告(gkd-kit#3357)

src/apps/com.baidu.searchbox.lite.ts
=> feat(百度极速版):开屏广告

src/apps/tv.danmaku.bili.ts
=> feat(哔哩哔哩):青少年模式弹窗、首页-推荐视频卡片广告

src/apps/com.tencent.wemeet.app.ts
=> feat(腾讯会议):开屏广告

src/apps/com.crirp.zhipu.ts
=> feat(智谱): 启动页广告和首页今日要闻弹窗

src/apps/com.xhgd.jx.ts
=> feat(柠檬解析): 开屏广告、弹窗广告

src/apps/com.eg.android.AlipayGphone.ts
https://github.com/gkd-kit/subscription/issues/3332
=> feat(支付宝): 12306卡片广告

src/apps/com.cimoc.haleydu.ts
https://github.com/gkd-kit/subscription/issues/3369
=> feat(Cimoc): 开屏广告, 应用内弹窗

src/apps/com.zbx.ct.tvzhibo.ts
=> feat(手机电视高清直播): 开屏广告、弹窗广告（补充规则）

src/apps/info.muge.appshare.ts
=> feat(AppShare): 卡片式广告（补充规则）

src/apps/com.tencent.qqlive.ts
=> Fix(腾讯视频):开屏广告

src/apps/com.qinlin.edoor.ts
=> feat(亲邻开门): 弹窗广告

src/apps/com.alibaba.android.rimet.ts
=> fix(钉钉): 消息列表上方横幅广告

src/apps/cn.soulapp.android.ts
=> feat(Soul):青少年模式弹窗

src/apps/com.greenpoint.android.mc10086.activity.ts
https://github.com/gkd-kit/subscription/issues/3479
=> fix(中国移动): 权限弹窗

src/apps/tv.danmaku.bili.ts
=> fix(b站):開屏廣告（繁體系統下）

src/apps/com.mosoink.teach.ts
https://github.com/gkd-kit/subscription/issues/3490#issue-2057270159
=> feat(云班课): 首页广告

src/apps/com.huawei.android.totemweather.ts
=> feat(华为天气): 卡片式广告（补充规则）

src/apps/android.zhibo8.ts
=> feat(直播吧): 信息流广告（补充规则）

src/apps/com.tencent.mm.ts
=> feat(微信): 订阅号-展开更早的消息

src/apps/com.realtech.xiaocan.ts
=> feat(小蚕霸王餐): 开屏广告-穿山甲SDK（提高规则通用性）

src/apps/com.qiyi.video.lite.ts
=> feat(爱奇艺极速版): 开屏广告

src/apps/com.able.wisdomtree.ts
=> feat(知到): 开屏广告、升级提醒 规则优化

src/apps/com.yitong.mbank.psbc.ts
=> feat(邮储银行): 首页-浮窗广告

src/apps/downloadtwittervideo.twitterdownloader.twittervideodownloader.twittersaver.ts
=> feat(TwiTake): 评分弹窗(gkd-kit#3371)

src/apps/com.flyersoft.seekbooks.ts
=> feat(搜书大师): 开屏广告 规则优化(gkd-kit#3375)

src/apps/com.fbank.mobile.ts
=> feat(富民银行): 开屏广告(gkd-kit#3504)

src/apps/com.netease.cloudmusic.ts
=> feat(网易云音乐): 发现-顶部视频广告(gkd-kit#3449)

src/apps/com.hpbr.directhires.ts
=> feat(店长直聘): 更新弹窗(gkd-kit#3473)

src/apps/com.google.android.youtube.ts
- #3520
- 视频播放-跳过广告 规则优化
- 视频播放-赞助商广告 规则优化
- 订阅浮窗广告
=> feat(youtube): 视频播放-跳过广告、视频播放-赞助商广告、订阅浮窗广告(gkd-kit#3520)

src/apps/com.sankuai.meituan.ts
=> feat(美团): 新人返场特惠

src/apps/com.baidu.tieba.ts
=> feat(百度贴吧): 申请消息提醒（补充规则）

src/apps/com.jd.pingou.ts
=> feat(京喜): 底部申请定位浮窗

src/apps/cn.wps.moffice_eng.ts
=> feat(WPS Office): 首页-底部广告

src/apps/com.jd.jrapp.ts
=> feat(京东金融): 满意度打分弹窗

src/apps/com.youdao.dict.ts
=> feat(网易有道词典): 学习页面-弹窗广告（补充activityId）

src/apps/com.baidu.netdisk.ts
=> feat(百度网盘):幸运券包弹窗

src/apps/com.baidu.searchbox.ts
=> feat(百度):红包弹窗

src/apps/tw.com.gamer.android.animad.ts
=> feat(动画疯):年龄限制窗口

src/apps/gov.pianzong.androidnga.ts
=> feat(NGA玩家社区): 开屏广告（补充规则）

src/apps/com.xingin.xhs.ts
=> fix(小红书): 更新弹窗

src/apps/com.dragon.read.ts
=> feat(番茄免费小说):广告弹窗

src/apps/com.ss.android.article.news.ts
=> feat(今日头条):底部热榜弹窗

src/apps/com.paokeji.yiqu.ts
=> feat(喵趣漫画): 局部广告

src/apps/com.mostone.life.ts
=> feat(默往): 开屏广告

src/apps/com.tencent.mobileqq.ts
=> fix(QQ): 好友动态-广告卡片二次点击失效（补充activityId）

src/apps/com.delicloud.app.smartoffice.ts
=> feat(得力e+):开屏广告

src/apps/com.tvbc.maiduidui.ts
=> feat(埋堆堆): 青少年弹窗

src/apps/com.tencent.mobileqq.ts
=> feat(QQ) 分段广告-好友动态-广告卡片（补充 activityId）、更新提示（补充规则）

src/apps/com.tencent.mobileqq.ts
=> fix(QQ)：开屏广告误触

src/apps/com.eg.android.AlipayGphone.ts
=> feat(支付宝):花呗升级弹窗(补充规则)

src/apps/com.diershoubing.erbing.ts
https://github.com/gkd-kit/subscription/issues/3797
=> feat(二柄): 分段广告

src/apps/com.xiaoenai.app.ts
https://github.com/gkd-kit/subscription/issues/3796
=> feat(小恩爱): 开屏, 弹窗

src/apps/com.tencent.mm.ts
=> feat(微信):分段广告-朋友圈广告

src/apps/com.netease.cloudmusic.ts
=> feat(网易云音乐) 分段广告（优化规则）

src/apps/com.netease.mail.ts
- 【开屏广告】- 开屏有个无效跳过按钮需排除
- 【查看成就】- 新增
=> feat(网易邮箱大师):开屏广告、全屏广告-查看成就

src/apps/com.nowcoder.app.florida.ts
=> feat(牛客): 开屏广告

src/apps/com.firebear.androil.ts
=> feat(小熊油耗): 开屏广告

src/apps/com.excean.na.ts
=> feat(99手游加速器):局部广告、首页弹窗广告

src/apps/com.taobao.taobao.ts
=> feat(淘宝):花呗升级弹窗(补充规则)

src/apps/cn.mil.junhao.ts
=> feat(中国军号): 开屏广告、功能类-首页右侧浮窗、功能类-意见反馈浮窗

src/apps/com.x.istar.ts
=> feat(观星): 全屏广告-开屏广告弹窗

src/apps/com.tencent.androidqqmail.ts
旧规则在 https://i.gkd.li/import/13963396 误触
=> fix(QQ邮箱) 开屏广告（修复误触）

src/apps/com.mymoney.ts
全局规则因为该应用存在特殊开屏规则而被排除，导致原该被全局跳过的广告无法跳过 @lisonge
=> feat(随手记): 开屏广告（补充规则）

src/apps/com.realtech.xiaocan.ts
https://github.com/gkd-kit/subscription/issues/3643
=> fix(小蚕霸王餐): 提高开屏广告兼容性
